### ISSUE TITLE
Using node-sp-auth to make REST call to SharePoint Online from NodeJS hosted in Azure ServiceApp

### ISSUE THREAD

**Issue by andreasblueher** [s-KaiNet/node-sp-auth#10]
Hey,

I've been trying to make a call to http://sharepointurl/_api/web/lists('guid')/subscriptions from NodeJS to create a webhook for a specific SharePoint library. Using node-sp-auth I'm able to do the first authentication and I'm receiving both tokens, but when I try to do the _api call afterwards I'm receiving an 403 Forbidden error message every time.

Do you have any idea if this issue could be node-sp-auth related or rather azure related or if SharePoint Online needs some kind of specific settings?

**Comment by s-KaiNet** [comment]
I think you are not attaching request digest to your post http request.   
You need to do something similar to this one under [sp-request](https://github.com/s-KaiNet/sp-request#update-list-title) repository - get request digest and attach to http headers via `X-RequestDigest`

**Comment by s-KaiNet** [comment]
@andreasblueher did you able to resolve the issue?

**Comment by andreasblueher** [comment]
Thanks for asking. No I haven't been able to resolve my issue, but to be fair I didn't keep trying that hard. My boss told me to take another route anyway. I really would like to figure out what I was doing wrong but I guess I don't have the time to do it now.

Thanks for your fast reply and support! Keep up the good work
