### ISSUE TITLE
Error trying to authenticate to SharePoint Online

### ISSUE THREAD

**Issue by schurlinga** [s-KaiNet/node-sp-auth#11]
Hi,

I'm trying to use node-sp-auth to authenticate against SharePoint Online but i'm receiving following error:

{"name":"RequestError","message":"Error: connect ECONNREFUSED 104.??.???.18:443","cause":{"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect","address":"104.??.???.18","port":443},"error":{"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect","address":"104.??.???.18","port":443},"options":{"simple":false,"strictSSL":false,"json":true,"form":{"login":"schurlinga@company.com"},"uri":"https://login.microsoftonline.com/GetUserRealm.srf","method":"POST","resolveWithFullResponse":false,"transform2xxOnly":false}}

When i use On-Premise url and creds it is working well.

Code: 
spauth
    .getAuth('https://company.sharepoint.com/sites/test/', {
        username: 'schurlinga@company.com',
        password: '****'
    })
    .then(function (data) {
     ...
    })
    .catch(function (error) {
        console.log(error);
        res.send(error);
    });

Thx for any help!

**Comment by s-KaiNet** [comment]
I guess you are using proxy. You need to configure proxy for nodejs. For reference, please take a look [here](https://github.com/s-KaiNet/gulp-spsave/issues/23)

**Comment by schurlinga** [comment]
Thx for the tip with the proxy.

Now i am getting an Access Denied Error despite the fact that i have full access to the requested site/url:
Error: <s:Fault>
  <s:Code>
    <s:Value>s:Sender</s:Value>
    <s:Subcode>
      <s:Value xmlns:a="http://docs.oasis-open.org/ws-sx/ws-trust/200512">a:FailedAuthentication</s:Value>
    </s:Subcode>
  </s:Code>
  <s:Reason>
    <s:Text xml:lang="en-IE">MSIS7068: Access denied.</s:Text>
  </s:Reason>
  <s:Detail>
    <IssuanceAuthorizationFault xmlns="http://schemas.microsoft.com/ws/2009/12/identityserver/" xmlns:i="http://www.w3.org/2001/XMLSchema-instance"/>
  </s:Detail>
</s:Fault>

So authentication seems to work but at some point not. Don't know if the problem is the adfs server or node-sp-auth...

**Comment by s-KaiNet** [comment]
Can you please send me full stack trace, if available?

**Comment by schurlinga** [comment]
Error: <s:Fault>
  <s:Code>
    <s:Value>s:Sender</s:Value>
    <s:Subcode>
      <s:Value xmlns:a="http://docs.oasis-open.org/ws-sx/ws-trust/200512">a:FailedAuthentication</s:Value>
    </s:Subcode>
  </s:Code>
  <s:Reason>
    <s:Text xml:lang="en-IE">MSIS7068: Access denied.</s:Text>
  </s:Reason>
  <s:Detail>
    <IssuanceAuthorizationFault xmlns="http://schemas.microsoft.com/ws/2009/12/identityserver/" xmlns:i="http://www.w3.org/2001/XMLSchema-instance"/>
  </s:Detail>
</s:Fault>
    at [application]\node_modules\node-sp-auth\lib\src\utils\AdfsHelper.js:34:23
    at tryCatcher ([application]\node_modules\bluebird\js\release\util.js:16:23)
    at Promise.module.exports.Promise._settlePromiseFromHandler ([application]\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise.module.exports.Promise._settlePromise ([application]\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise.module.exports.Promise._settlePromise0 ([application]\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise.module.exports.Promise._settlePromises ([application]\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue ([application]\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues ([application]\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.e.Async.drainQueues ([application]\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)

**Comment by s-KaiNet** [comment]
Do you use any third-party federation provider (ping identity for example)?

**Comment by schurlinga** [comment]
According to the ADFS Server Colleague, for O365 only ADFS is used.

**Comment by s-KaiNet** [comment]
Ok, can you please make a test with .NET CSOM object model?
Try to run below code: 

```csharp
using (ClientContext clientContext = new ClientContext("https://yoursite.sharepoint.com/"))
{
    SecureString passWord = new SecureString();

    foreach (char c in "yourpassword".ToCharArray()) passWord.AppendChar(c);

    clientContext.Credentials = new SharePointOnlineCredentials("loginname@yoursite.onmicrosoft.com", passWord);
    clientContext.Load(clientContext.Web);
    clientContext.ExecuteQuery();
} 
```
In case if you don't have an access to the Visual Studio I can send you the console application so you can run it.   
Besides, does your password contain any special symbols apart letters and digests? If yes, can you please post those symbols?

**Comment by schurlinga** [comment]
With .NET CSOM it works perfect.

Password contains '$', but the Password seems to work, because when i use a wrong password i get following error: ID3242: The security token could not be authenticated or authorized.

**Comment by s-KaiNet** [comment]
Another question: do you have multi-factor authentication with ADFS?

**Comment by s-KaiNet** [comment]
Another one: Can you try to run the code from environment without proxy? May be proxy is the issue.

**Comment by schurlinga** [comment]
Same Access Denied error on environment without proxy.

No multi-factor authentication with ADFS. Just Username and password.

**Comment by schurlinga** [comment]
Have you tested node-sp-auth with Single Sign On? Maybe this causes the error?

**Comment by schurlinga** [comment]
The Problem is somewhere in this request:

    return request.post(usernameMixedUrl, {
                body: samlBody,
                strictSSL: false,
                simple: false,
                headers: {
                    'Content-Length': samlBody.length,
                    'Content-Type': 'application/soap+xml; charset=utf-8'
                }
            })
                .then(function (xmlResponse) { // xmlResponse is always with Access Denied

When i make the request with [Advanced Rest Client](https://chrome.google.com/webstore/detail/advanced-rest-client/hgmloofddffdnphfgcellkdfbfbjeloo) and use the same headers and same samlBody the request succeeds and i get the correct xmlResponse.

**Comment by schurlinga** [comment]
For the sake of completeness:

 **IssuanceAuthorizationFault xmlns="http://schemas.microsoft.com/ws/2009/12/identityserver/" xmlns:i="http://www.w3.org/2001/XMLSchema-instance"**

github always removed the detail error info, maybe this helps solving the problem.

**Comment by s-KaiNet** [comment]
Yes I've tested SSO with ADFS on three different environments (one configured by me, two others are customers).    

May be it does work with advanced rest client because you are running in context of the browser, nodejs (with proxy in your case) is completely different thing.   
I tend to think your ADFS server configured somehow which prevents successful authentication.     
Unfortunately I'm running out of ideas and can propose only two things (both not good for you I guess):  

 1. Give me read only access to your site collection via dedicated user so I can figure it out.
2. Use other authentication option (addin only)

**Comment by schurlinga** [comment]
Yesterday i tried with another customers sp online and it worked (adfs with
two factor auth), so i also think it is some adfs server configuration
which causes this error.

For now i switched to csom, but i will try to fix this adfs configuration
anyway. Will let you know what it was.

Until then thx for the help and the quick responses!

Br
Sergei Sergeev <notifications@github.com> schrieb am Sa. 8. Apr. 2017 um
00:43:

**Comment by simkessy** [comment]
I'm also having issues with authentication.

Error: **The entered and stored passwords do not match.**

We have 2 Factor Authentication enabled, i'm not sure if that has an impact. 

I get this error: 
```
[14:59:44] spsave: Error: <S:Fault>
  <S:Code>
    <S:Value>S:Sender</S:Value>
    <S:Subcode>
      <S:Value>wst:FailedAuthentication</S:Value>
    </S:Subcode>
  </S:Code>
  <S:Reason>
    <S:Text xml:lang="en-US">Authentication Failure</S:Text>
  </S:Reason>
  <S:Detail>
    <psf:error>
      <psf:value>0x80048821</psf:value>
      <psf:internalerror>
        <psf:code>0x80041012</psf:code>
        <psf:text>The entered and stored passwords do not match.</psf:text>
      </psf:internalerror>
    </psf:error>
  </S:Detail>
</S:Fault>
    at OnlineUserCredentials.postToken (C:\Users\Administrator\Dropbox\projects\r3interworks\nrg\nrg.sp.pwa\node_modules\node-sp-auth\lib
\src\auth\resolvers\OnlineUserCredentials.js:150:19)
    at C:\Users\Administrator\Dropbox\projects\r3interworks\nrg\nrg.sp.pwa\node_modules\node-sp-auth\lib\src\auth\resolvers\OnlineUserCre
dentials.js:47:26
    at processImmediate [as _immediateCallback] (timers.js:383:17)
Unhandled rejection Error in plugin 'gulp-spsave'
Message:
    <S:Fault>
  <S:Code>
    <S:Value>S:Sender</S:Value>
    <S:Subcode>
      <S:Value>wst:FailedAuthentication</S:Value>
    </S:Subcode>
  </S:Code>
  <S:Reason>
    <S:Text xml:lang="en-US">Authentication Failure</S:Text>
  </S:Reason>
  <S:Detail>
    <psf:error>
      <psf:value>0x80048821</psf:value>
      <psf:internalerror>
        <psf:code>0x80041012</psf:code>
        <psf:text>The entered and stored passwords do not match.</psf:text>
      </psf:internalerror>
    </psf:error>
  </S:Detail>
</S:Fault>
```

**Comment by s-KaiNet** [comment]
Via private conversation with @simkessy we found an issue with SharePoint Online and two-factor authentication (without ADFS, but just pure Azure AD two-factor).   
If you have two-factor configured and trying to use username and password in order to authenticate in SharePoint Online, you will get an error `The entered and stored passwords do not match` (not very descriptive).  
What you need to do, is to use App Password instead of you real password. Use this link to add a new app password - [Create an app password for Office 365](https://support.office.com/en-us/article/Create-an-app-password-for-Office-365-3e7c860f-bda4-4441-a618-b53953ee1183?ui=en-US&rs=en-US&ad=US)

**Comment by s-KaiNet** [comment]
@schurlinga 
that's a long story, but new on-demand authentication options were added which might help in your case.  
If someone else experience such kind of issue, please try on-demand option.

**Comment by s-KaiNet** [comment]
If you are struggling with authentication issues, try ondemand auth option.   
I'm closing this one.

**Comment by ushroff79** [comment]
we have multi-factor authentication with ADFS. getting error The sign-in name or password does not match one in the Microsoft account system.
below is code:
var username = "xx@company.com";
            var password = "xxxx~";
            var endPoint = "https://company.sharepoint.com/sites/SPDeveloper";
            var stsEndpoint = "https://login.microsoftonline.com/extSTS.srf";
            var signInUrl = "https://company.sharepoint.com/_forms/default.aspx?wa=wsignin1.0";
            var browserHost = "company.sharepoint.com"; //e.g. mycompany.sharepoint.com 
            var browserUserAgent = "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36";

            var cookies = new CookieContainer();
            var executingPath = Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location);
            var payLoadSts = System.IO.File.ReadAllText(Path.Combine(executingPath, "extStsTemplate.xml")).Replace("{USERNAME}", username).Replace("{PASSWORD}", password).Replace("{ENDPOINTREFERENCE}", endPoint);
         
            //var payLoadSts = SMAL.Replace("{USERNAME}", username).Replace("{PASSWORD}", password).Replace("{ENDPOINTREFERENCE}", endPoint);

            // webrequest 0 
            // webrequest 0: get the RpsContextCookie 
            // webrequest 0 
            string requiredAuthUrl = string.Format("{0}/_layouts/15/Authenticate.aspx?Source={1}", endPoint, HttpUtility.UrlDecode(endPoint));
            HttpWebRequest request0 = (HttpWebRequest)WebRequest.Create(requiredAuthUrl);
            request0.Accept = "*/*";
            request0.Headers.Set(HttpRequestHeader.AcceptLanguage, "en-US");
            request0.Headers.Set(HttpRequestHeader.AcceptEncoding, "gzip, deflate");
            request0.UserAgent = browserUserAgent;
            request0.AllowAutoRedirect = false;
            request0.CookieContainer = cookies;

            var response0 = (HttpWebResponse)request0.GetResponse();

            // webrequest 1
            // webrequest 1: login
            // webrequest 1
            var request1 = (HttpWebRequest)WebRequest.Create(stsEndpoint);
            request1.CookieContainer = cookies;
            var data = Encoding.ASCII.GetBytes(payLoadSts);

            request1.Method = "POST";
            request1.ContentType = "application/xml";
            request1.ContentLength = data.Length;

            using (var stream1 = request1.GetRequestStream())
            {
                stream1.Write(data, 0, data.Length);
            }

            // Response 1
            var response1 = (HttpWebResponse)request1.GetResponse();
            var responseString = new StreamReader(response1.GetResponseStream()).ReadToEnd();

            // Get BinarySecurityToken
            var xData = XDocument.Parse(responseString);
            var namespaceManager = new XmlNamespaceManager(new NameTable());
            namespaceManager.AddNamespace("S", "http://www.w3.org/2003/05/soap-envelope");
            namespaceManager.AddNamespace("wst", "http://schemas.xmlsoap.org/ws/2005/02/trust");
            namespaceManager.AddNamespace("wsse", "http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd");
            var BinarySecurityToken = xData.XPathSelectElement("/S:Envelope/S:Body/wst:RequestSecurityTokenResponse/wst:RequestedSecurityToken/wsse:BinarySecurityToken", namespaceManager);

**Comment by s-KaiNet** [comment]
For .net I recommend you to use [PnP .NET Component](https://github.com/SharePoint/PnP-Sites-Core) with [Authentication Manager](https://dev.office.com/blogs/Introduction-to-authentication-manager-in-pnp-core-library) from there.
