### ISSUE TITLE
Special characters in password in ADFS scenario

### ISSUE THREAD

**Issue by koltyakov** [s-KaiNet/node-sp-auth#12]
Special characters (like `&`) in the password cause an issue with auth with ADFS OnPremises scenario.
Response from `https://${adfsHost}/adfs/services/trust/13/usernamemixed` within `./lib/src/utils/AdfsHelper.js` return empty string.
Replacing `&` to `&amp;` in the config leads to a successful authentication, so other parameters like `relyingParty` and `adfsUrl` are correct.
I know that special characters caused issues sometime before and guess that is was not applied to ADFS scenario.

P.S. Not a critical issue as the workaround works for now. Just, it would be great to be fixed in future.

**Comment by s-KaiNet** [comment]
Thank you for reporting, Andrew, fixed in 1.3.3 version.
