### ISSUE TITLE
Error authenticating to SharePoint On-Premise

### ISSUE THREAD

**Issue by ismet** [s-KaiNet/node-sp-auth#13]
Hi,

I'm trying to connect to SharePoint 2016 on-premise from my simple Vue.js application which is hosted locally. Both client (my pc) and SP server are in the same network/domain.

The code is the following:
```
var spauth = require('node-sp-auth');

spauth.getAuth('http://spdev/', {
	username: 'sp_user',
	password: 'sp_password',
	domain: 'spdomain'
})
.then(function (options) {
  console.log(options);
})
.catch(function (err) {
  console.log(err);
});
```

When I run the app, I am getting the following errors for each browser:

```
[Chrome] Fetch API cannot load http://spdev/. Response for preflight is invalid (redirect)

[Firefox] Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://spdev/. (Reason: CORS preflight channel did not succeed).

[IE] SEC7126: Redirects are not allowed for CORS preflight requests. SCRIPT7002: XMLHttpRequest: Network Error 0x80070005, Access is denied.

[EDGE] HTTP401: DENIED - The requested resource requires user authentication.  (Fetch)OPTIONS - http://spdev/
```

The CORS settings in IIS are;
```
Access-Control-Allow-Origin: *
Access-Control-Request-Headers: X-Requested-With, Origin, Content-Type, Accept, Authorization
Access-Control-Request-Methods: GET, PUT, POST, DELETE, HEAD, OPTIONS
Access-Control-Allow-Credentials: true
```

I have double checked url, username, password, etc.. I am not behind a proxy.. So, what can be the cause of this issue? How can I solve it?

**Comment by koltyakov** [comment]
Hi @ismet,

The library was designed for Node.js environment. I'm not sure, is it a good idea of using it in a browser's context. @s-KaiNet, what do you think? I, personally, wouldn't recommend hassling with SharePoint CORS options.

---

But...

Maybe it will suit you, Ismet. For the type of development workflow what you've described we use [sp-rest-proxy](https://github.com/koltyakov/sp-rest-proxy), which allows mapping the proxy with target SharePoint web, defining user account. The proxy uses node-sp-auth and sp-request on the background.

It can run simultaneously with your local serve task, e.g.:

```json
// package.json
...
"scripts": {
    "serve": "concurrently --kill-others \"npm run proxy\" \"npm run webapp\"",
    "proxy": "node ./src/proxy",
    "webapp": "gulp serve"
}
...
```
```bash
npm run serve
```
starts proxy, i.e. on http://localhost:9090 and your app dev instalce on http://localhost:8080.

The app sends requests to http://localhost:9090/_api/web/... which routed to your SharePoint web.
The app just takes care replacing http://localhost:9090 to http://spdev when it is deployed to SharePoint environment, and emulated faked request digest in a local mode.

**Comment by ismet** [comment]
Hi @koltyakov,

Thanks for the detailed comments.. I have tried sp-rest-proxy and it just worked.. That's the solution I've been looking for some time..  Now I have a local hosted client application running in a browser and pulling data directly from SharePoint without any hassles.. 

You guys, keep up doing great job...

**Comment by s-KaiNet** [comment]
Hi guys, Andrew, as usual, thank you for your great answer.  
@ismet everything Andrew said is correct. The module intended to use with node.js environment only and not in a browser. Glad to know with help of Andrew you found a way to go!
