### ISSUE TITLE
AuthResolverFactory.ts - resolve OnlineAddinOnly before OnlineUserCredentials

### ISSUE THREAD

**Issue by DouglasCAyers** [s-KaiNet/node-sp-auth#14]
First, thanks for this great plugin!

Second, I'm writing nodejs app to post new files to SharePoint and although I have the **username** and **password** for `OnlineUserCredentials` auth, I also have **clientId** and **clientSecret** for `OnlineAddinOnly` auth.

Currently, the `AuthResolverFactory` class resolves `OnlineUserCredentials` before `OnlineAddinOnly`. Meaning, if I try to use **sp-request** to post a file to SharePoint then I must include the **X-RequestDigest** header.

However, the **X-RequestDigest** header is not a requirement when authenticating via oauth. [reference](https://dev.office.com/sharepoint/docs/sp-add-ins/complete-basic-operations-using-sharepoint-rest-endpoints).
> Another important consideration when creating, updating, and deleting SharePoint entities is that if you aren't using OAuth to authorize your requests, these operations require the server's request form digest value as the value of the  X-RequestDigest header.
> If you're using the authentication and authorization flow described in Authorization and authentication of SharePoint Add-ins, you don't need to include the request digest in your requests.

For example, with credentials options as:
```
{
    username : 'myuser',
    password : 'mypass',
    clientId: 'myclientid',
    clientSecret: 'myclientsecret'
}
```
Even though I have specified oauth clientId and clientSecret the auth resolver only does `OnlineUserCredentials` because it sees **username** [reference](https://github.com/s-KaiNet/node-sp-auth/blob/master/src/auth/IAuthOptions.ts#L59) and I'm required to query for and use **X-RequestDigest** header in my POST requests.

I tested locally by editing `<mydir>/node_modules/node-sp-auth/lib/src/auth/resolvers/AuthResolverFactory.js` by swapping the order of the two IF conditions [at lines 23-29](https://github.com/s-KaiNet/node-sp-auth/blob/master/src/auth/AuthResolverFactory.ts) and this resolved to `OnlineAddinOnly` first which allowed me to **not** include the **X-RequestDigest** header.

What are your thoughts on this approach? If you agree I can submit a pull request.

Thanks!

Doug

**Comment by DouglasCAyers** [comment]
Here are examples using `sp-request` module in nodejs to show the difference.

# OnlineUserCredentials

Requires the **X-RequestDigest** header.

```
var spr = require('sp-request');

var spClient = spr.create({
    username : process.env.OAUTH_SHAREPOINT_USERNAME,
    password : process.env.OAUTH_SHAREPOINT_PASSWORD,
    clientId: process.env.OAUTH_SHAREPOINT_CLIENT_ID,
    clientSecret: process.env.OAUTH_SHAREPOINT_CLIENT_SECRET
});

var digest;

var folderPath = 'Documents/myFolder';
var fileName = 'myfile.txt';
var fileData64 = 'Hello World';

spClient.requestDigest( `${process.env.SHAREPOINT_URL}/sites/${process.env.SHAREPOINT_SITE_NAME}` )
.then( function( digestResponse ) {

    digest = digestResponse; // save digest for subsequent POST requests

}).then( function() {

    return spClient.post( `${process.env.SHAREPOINT_URL}/sites/${process.env.SHAREPOINT_SITE_NAME}/_api/web/GetFolderByServerRelativeUrl('${encodeURIComponent(folderPath)}')/Files/Add(overwrite=true,url='${encodeURIComponent(fileName)}')`, {
        body: fileData64,
        headers: {
            'X-RequestDigest' : digest
        }
    });

});
```

# OnlineAddinOnly

With my edit to `AuthResolverFactory.js` to resolve `OnlineAddinOnly` before `OnlineUserCredentials` then requests do **not** require the **X-RequestDigest** header.

```
var spr = require('sp-request');

var spClient = spr.create({
    username : process.env.OAUTH_SHAREPOINT_USERNAME,
    password : process.env.OAUTH_SHAREPOINT_PASSWORD,
    clientId: process.env.OAUTH_SHAREPOINT_CLIENT_ID,
    clientSecret: process.env.OAUTH_SHAREPOINT_CLIENT_SECRET
});

var folderPath = 'Documents/myFolder';
var fileName = 'myfile.txt';
var fileData64 = 'Hello World';

spClient.post( `${process.env.SHAREPOINT_URL}/sites/${process.env.SHAREPOINT_SITE_NAME}/_api/web/GetFolderByServerRelativeUrl('${encodeURIComponent(folderPath)}')/Files/Add(overwrite=true,url='${encodeURIComponent(fileName)}')`, {
    body: fileData64
});
```

**Comment by s-KaiNet** [comment]
Hi Doug,    
I don't understand your point clearly. These options  
```javascript
{
    username : 'myuser',
    password : 'mypass',
    clientId: 'myclientid',
    clientSecret: 'myclientsecret'
}
```  
are not allowed, because you are trying to mix different authentication strategies.   
You can use either username\password or clientId\clientSecret combination. Why do you need combine them into one object?    
If you want to utilize two auth options, you need to create two different sprequest objects:  
```javascript
var spr1 = spr.create({username: 'user', password: 'pass'});
var spr2 = spr.create({clientId: '', clientSecret: ''});
```  
Does it work for you?

**Comment by DouglasCAyers** [comment]
Well, yes, that does work just specifying clientId and clientSecret!

I didn't even try that thinking I'd surely have to provide user/pass somewhere; either known at server level or go through an interactive oauth authorization web flow.

Did not realize just clientId and clientSecret are sufficient -- so they are treated essentially like username and password too, eh? All actions then default as the user who created the oauth app? Strange it works without being told the specific user.

Thanks!

**Comment by DouglasCAyers** [comment]
For anyone else who stumbles upon this conversation and is new to SharePoint authentication, I think the reason the `OnlineAddinOnly` authentication strategy works with only **clientId** and **clientSecret** is that when granting permissions to my oauth app the `AllowAppOnlyPolicy="true"` was specified.

Example:
---
https://[domain].sharepoint.com/sites/[sitename]/_layouts/15/appinv.aspx
```
<AppPermissionRequests AllowAppOnlyPolicy="true">
 <AppPermissionRequest Scope="http://sharepoint/content/sitecollection" Right="Write"/>
</AppPermissionRequests>
```

If I understand correctly, then according to https://dev.office.com/sharepoint/docs/sp-add-ins/add-in-authorization-policy-types-in-sharepoint then when authenticating with only clientId and clientSecret that is an elevated request able to perform requests with privileges that perhaps a named user might not have permission to do.

**Comment by s-KaiNet** [comment]
You're right, in oauth world there are different authentication grants (or flows).   
The one used in node-sp-auth called Client Credentials grant. It uses only clientId and clientSecret in order to obtain an access token and all actions in SharePoint with this access token considered as behalf on the app (no user). In order to "enable" this kind of grant we need to explicitly provide `AllowAppOnlyPolicy="true"` in our app manifest.

**Comment by DouglasCAyers** [comment]
Thanks for the guidance and help @s-KaiNet !
