### ISSUE TITLE
Electron fails when there is a space in the path

### ISSUE THREAD

**Issue by lfastrup** [s-KaiNet/node-sp-auth#15]
I'm using gulp-spsave with ondemand authentication from VS Code on Windows.
The credential object for spsave is:
var spsaveCredential = { ondemand: true, electron: require("electron"), force: false, persist: true }

If I have a space in the project path then I get an error like this:

Command failed: cmd.exe /c D:\Source\Repos\Sample Project\node_modules\electron\dist\electron.exe D:\Source\Repos\Sample Projects\node_modules\
node-sp-auth\lib\src\auth\resolvers\ondemand\electron\main.js 

I can work-around the error by not having a space in the path.

**Comment by s-KaiNet** [comment]
Hi Lars,   
thanks for reporting, I will take a look.

**Comment by s-KaiNet** [comment]
Fixed in 2.2.4, please give it a try and say if it works for you.

**Comment by lfastrup** [comment]
Good job - the upgrade also solved this issue :-) Thanks again.
