### ISSUE TITLE
Ondemand authentication does not work with ADFS on-premises

### ISSUE THREAD

**Issue by lfastrup** [s-KaiNet/node-sp-auth#16]
I'm attempting to use gulp-spsave to remotely upload files to SharePoint 2013 on-premises. SharePoint is exposed through a Windows Server 2016 Web Application Proxy. Authentication is handled by ADFS 4.0 on a dedicated Windows Server 2016 VM. User login works perfectly through any browser.

The ADFS relying party is a non-claims aware one. That is, WAP and ADFS uses Kerberos to authenticate the user with SharePoint. Not SAML.

The credential object for gulp-spsave is:
`var spsaveCredential = { 
  ondemand: true, 
  electron: require("electron"), 
  force: false, 
  persist: true 
}
`
This correctly opens an electron browser window with the ADFS login form. Login is also successful.

But the electron window does not close again! It just shows the XML result from SharePoint from the first HTTP request issues by gulp-spsave. In my case this request:
https://demo.mydomain.com/_api/Web/GetFileByServerRelativeUrl('/SiteAssets/Main.js')

The XML shown in the electron window is a valid XML response from SharePoint with details about the requested file Main.js. This shows that authentication works. 

But the window should close and the auth cookie should be stored for future requests. This does not happen.

Any ideas?

**Comment by s-KaiNet** [comment]
wow, that looks weird.   
I've tested on my local setup with ADFS, it works fine. I will try to make the test once again. Thanks for reporting!

**Comment by lfastrup** [comment]
Great - thanks for you prompt action! I can send you a demo login to my system if you like. I have not tested if the issue has to do with ADFS 2.0 / 3.0 / 4.0   
I only have ADFS 4.0

**Comment by s-KaiNet** [comment]
> I can send you a demo login to my system if you like.    

That would be ideal! You can find my email via github profile.

**Comment by s-KaiNet** [comment]
Oops closed automatically by commit...
node-sp-auth@2.2.2 is out which fixes your issue. Please try it (I recommend to remove `node_modules` completely and reinstall).

**Comment by lfastrup** [comment]
Thanks a ton! It works for me now. Your fast response and resolution is much appreciated :-)
