### ISSUE TITLE
getAuth is failed with "unexpected close tag"

### ISSUE THREAD

**Issue by arepalli-praveenkumar** [s-KaiNet/node-sp-auth#18]
I tried to authorize myself using company Email-ID & Password .
Simple block of code tried

    import * as spAuth from "node-sp-auth";
	export class ExampleClass {
		public async verify() {
			spAuth.getAuth("https://mycompany.sharepoint.com/sites/dev", {
			username: "official-mail-id",
			password: "**********"
 		});
 		}
    }

The same code was working week ago and now it is failing 
it is successful when i login through browser but failed through application code. 
Any help is appreciated

**Comment by koltyakov** [comment]
Hey Praveenkumar,

`username` parameter for SharePoint Online should be in the following format: `[username]@[domain.com]`

E.g. official-mail-id@mycompany.onmicrosoft.com

**Comment by s-KaiNet** [comment]
If your code worked one week ago, then it's a very low chance that node-sp-auth is the cause, because last update was 10 days ago. 
I guess something changed in you SharePoint or user configuration (changed auth or added MFA or whatever)

**Comment by praveenkumararepalliGit** [comment]
@s-KaiNet I have talked to my sharePoint admin about recent user configuration, Looks like this can be a proxy issue.

Thank you for immediate reply.

**Comment by praveenkumararepalliGit** [comment]
@koltyakov corporate proxy not allowing us to go in. Thank you

**Comment by koltyakov** [comment]
For a proxy, how about this setting? https://github.com/s-KaiNet/gulp-spsave/issues/23

**Comment by arepalli-praveenkumar** [comment]
I have tried this but no luck.....my onshore team also investigation same

**Comment by s-KaiNet** [comment]
I would recommend you to try .net version to see if it works:     
```csharp
using (var clientContext = new ClientContext("https://yoursite.sharepoint.com/"))
{
    var passWord = new SecureString();

    foreach (char c in "yourpassword") passWord.AppendChar(c);

    clientContext.Credentials = new SharePointOnlineCredentials("loginname@yoursite.onmicrosoft.com", passWord);
   clientContext.Load(clientContext.Web);
   clientContext.ExecuteQuery();
} 
```

**Comment by s-KaiNet** [comment]
@arepalli-praveenkumar Have you tried .net version? Do you still have the issue?
