### ISSUE TITLE
fails to build with create-react-app

### ISSUE THREAD

**Issue by kayodebristol** [s-KaiNet/node-sp-auth#19]
following error is generated: 
./node_modules/rx-lite-aggregates/rx.lite.aggregates.js
Module not found: Can't resolve './rx.lite' in '..\node_modules\rx-lite-aggregates'

The about can be fixed by editing rx-lite-aggregates to look for '../rx-lite/rx.lite'. But after this, another build error, then another, then another. Is there anyone using this with react? 

Steps to reproduce. 

1. create-react-app, then test it with npm run start
2. npm install node-sp-auth --save-dev
3. use node in code (add import * as spauth from 'node-sp-auth'; to app.js)
4. npm run start [build errors]

**Comment by koltyakov** [comment]
`node-sp-auth` is the library for server-side usage within Node.js V8/ChakraCore processes.
It can't be bundled to a client-side script. At the same time, it's theoretically feasible to use react and node-sp-auth together for a server-side rendering when a script is created for the Node.js process. But it's definitely not the case of the actions described in reproduce steps.

**Comment by kayodebristol** [comment]
Koltyakov, 
Thanks for your help.  I was looking for a way to develop outside of SharePoint using  pnp & react-redux pointing to SharePoint for data during Dev only.  Then run build and deploy to SharePoint  in a cewp with as little code changes  as possible (zero changes would be great). 


End goal,  allow a group of designer with heavy infopath skills and basic JavaScript (jquery mostly) to transition to react with as little pain as possible.  Vscode with npm run start is great for the ui portion,  but getting data without deploying SharePoint has left me scratching my head these past few days. 

I was initially trying to getting your proxy project to work with concurrently js. So I can do something like:
"scripts": {
   "start": "concurrently \"react-scripts start\" \". node . /server.js \""

**Comment by koltyakov** [comment]
Gotcha! For this use case, I would recommend adding [sp-rest-proxy](https://github.com/koltyakov/sp-rest-proxy) to your dev toolchain. The proxy uses `node-sp-auth` and some other libraries and allows requesting SharePoint REST API with CORS mode.

So you can run your react app serve in its port and sp-rest-proxy on another.

There are some details in our gitter chat, also new questions are welcome there.

**Comment by kayodebristol** [comment]
Thanks. Still trying to iron out the integration... sp-rest-proxy runs great in a separate project when I git clone it.... looks like I'm not making the appropriate changes to the example that are required if sp-rest-proxy is used as a module, like the path to staticRoot. 
This seems to work:   staticRoot: './node_modules/sp-rest-proxy/static'   
Whereas the [example](https://github.com/koltyakov/sp-rest-proxy#how-to-use-as-a-module)  says: staticRoot: './static' . 

I'll move the conversation over to [sp-rest-proxy](https://github.com/koltyakov/sp-rest-proxy). It's an incredible and useful module and I'd like to help make it better, in some small way, if I can. Even if that just means making it more accessible to relative newbies like myself.

**Comment by koltyakov** [comment]
https://github.com/koltyakov/sp-rest-proxy/issues/32 we can continue here.

**Comment by koltyakov** [comment]
@kayodebristol,

I've added end-to-end example in the issue response.
Please check if it works for you?

**Comment by s-KaiNet** [comment]
Cool guys that you had managed to resolve the issue.    
Andrew thank you for handling it :)
