### ISSUE TITLE
Unable to login with Online User Credentials (`set-cookie` header missing from response)

### ISSUE THREAD

**Issue by matthewrobb** [s-KaiNet/node-sp-auth#20]
When trying to pull the FedAuth data from the `set-cookie` header on the form post response I am getting errors thrown due to it not being present there.

If I pull my tokens from the browser and hard code them in OnlineUserCredentials.js it does work.

**Comment by s-KaiNet** [comment]
Hi Robb,  
do you use 2FA? Do you use ADFS?

**Comment by matthewrobb** [comment]
So I am technically accessing a clients Sharepoint Online where I have been doing so for months. I provide node-sp-auth my `me@my-company.com` and password. It's only recently that it has started to fail. Locally the only changes I have made are in node versions but I have tried to resolve the issue by downgrading (using nvm).

I guess it's possible that 2FA was added but I can still log in through the browser just fine.

**Comment by matthewrobb** [comment]
The process fails here: https://github.com/s-KaiNet/node-sp-auth/blob/master/src/auth/resolvers/OnlineUserCredentials.ts#L66

I stepped through the preceeding operations and they all seem to work including getting my auth token.

**Comment by s-KaiNet** [comment]
Could you please post the content of `response.headers` from that line (strip all sensitive information if any)?

**Comment by matthewrobb** [comment]
```json
{
  "cache-control": "no-cache, no-store",
  "pragma": "no-cache",
  "content-length": "23753",
  "content-type": "text/html; charset=utf-8",
  "expires": "-1",
  "p3p": "CP=\"ALL IND DSP COR ADM CONo CUR CUSo IVAo IVDo PSA PSD TAI TELo OUR SAMo CNT COM INT NAV ONL PHY PRE PUR UNI\"",
  "x-sharepointhealthscore": "2",
  "x-aspnet-version": "4.0.30319",
  "sprequestguid": "67352b9e-90cb-4000-790d-f47d76d98f10",
  "request-id": "67352b9e-90cb-4000-790d-f47d76d98f10",
  "ms-cv": "nis1Z8uQAEB5DfR9dtmPEA.0",
  "strict-transport-security": "max-age=31536000",
  "sprequestduration": "725",
  "spiislatency": "1",
  "x-powered-by": "ASP.NET",
  "microsoftsharepointteamservices": "16.0.0.7101",
  "x-content-type-options": "nosniff",
  "x-ms-invokeapp": "1; RequireReadOnly",
  "x-msedge-ref": "Ref A: A0CF6738F20A4534AE41DDF947F7E132 Ref B: BLUEDGE0817 Ref C: 2017-11-09T14:23:02Z",
  "date": "Thu, 09 Nov 2017 14:23:01 GMT",
  "connection": "close"
}
```

**Comment by s-KaiNet** [comment]
I have the same, except that `set-cookie` is present :)

**Comment by matthewrobb** [comment]
Could this have anything to do with Request and cookies?

**Comment by s-KaiNet** [comment]
I don't think so. Usually in SharePoint online everything works pretty predictable and similar. It works for me, doesn't work for you...  
I'm thinking why you don't receive cookie and for now I don't have any good idea. If 2FA is the cause, you will receive invalid credentials error, so that's not your case.     
Does [`on-demand`](https://github.com/s-KaiNet/node-sp-auth/wiki/On-demand-authentication) auth option work for you?

**Comment by s-KaiNet** [comment]
That's really strange.    
Can you please perform one additional check. Can you try .net version, like [this one](https://gist.github.com/s-KaiNet/5095f6b2cb6eafd37f43004c7fd85f4d) for example. Add load web and execute query to see if it works.
