### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by brunoferreira2007** [s-KaiNet/node-sp-auth#23]
I'm trying to use this package with Angular CLI, but doesn't seem to work.
I tried with a new Angular CLI project, with only this additional package. When I try to run it locally (ng serve), I'm getting a bunch of errors when compiling:

`ERROR in ./node_modules/rx-lite-aggregates/rx.lite.aggregates.js
Module not found: Error: Can't resolve './rx.lite' in 'C:\Test1\node_modules\rx-lite-aggregates'
resolve './rx.lite' in 'C:\Test1\node_modules\rx-lite-aggregates'` 

`ERROR in ./node_modules/cpass/dist/utils/machineId.js
Module not found: Error: Can't resolve 'child_process' in 'C:\Test1\node_modules\cpass\dist\utils'
resolve 'child_process' in 'C:\Test1\node_modules\cpass\dist\utils'`

`ERROR in ./node_modules/external-editor/main/index.js
Module not found: Error: Can't resolve 'child_process' in 'C:\Test1\node_modules\external-editor\main'
resolve 'child_process' in 'C:\Test1\node_modules\external-editor\main'`

...

Is this not compatible with Angular CLI?

**Comment by koltyakov** [comment]
Hi @brunoferreira2007,

This is for server-side usage (authenticating SharePoint within Node.js application). The library can't be bundled as browser's lib.

What you might look is running Angular locally with the capability of consuming SharePoint API? Please check [this approch](http://johnliu.net/blog/2017/9/angular-4-sharepoint-on-premises-localhost-development-and-sp-rest-proxy).

**Comment by brunoferreira2007** [comment]
Hi Andrew, thanks for the tip. I'm actually currently using you package "sp-rest-proxy" to consume the API locally.
What I wanted to achieve was to use pnp-js-core locally to build the application, and my only concern is that you have a remark saying that pnp POST requests will not work with "sp-rest-proxy" (I didn't test it).  So I was trying to somehow do a workaround, creating proxy to connect directly to my sharepoint web, but I'm always getting an "unauthorized" error. Is there a way to make pnp POST to work on a local run?
thanks for the info.

**Comment by koltyakov** [comment]
@brunoferreira2007, please check [this issue](https://github.com/koltyakov/sp-rest-proxy/issues/26)'s example. 
What you need is mimic `_spPageContextInfo` object when serving locally and define baseUrl explicitly.

**Comment by brunoferreira2007** [comment]
Thanks for the help
