### ISSUE TITLE
What sort of effort is required to run this on a browser?

### ISSUE THREAD

**Issue by mrozbarry** [s-KaiNet/node-sp-auth#24]
I'm attempting to do a pure-browser sign in flow, and this library looked the best, in terms of documentation, and being actively maintained. After importing it into my project (React 16, webpack 2, babel), I get a lot of modules that can't be found.

Most of the dependency issues seem to revolve around using the filesystem and implementing some sort of cli/ui system.  I thought this was a pure logic system to authentication - am I wrong in that assumption?

**Comment by s-KaiNet** [comment]
This library is not intended for the browser, it can be used from nodejs execution runtime only. That is why your webpack produces a lot of errors.   
However if you want to perform rest queries from web browser running on localhost to SharePoint, take a look [here](https://github.com/koltyakov/sp-rest-proxy/)

**Comment by mrozbarry** [comment]
Out of curiousity, why is there a hard requirement from nodejs directly?

Also, the environment I'm developing for doesn't allow me to run any nodejs/express servers, so I guess I'll just have to implement adfs/sharepoint auth myself.

Thanks for the quick response!

**Comment by s-KaiNet** [comment]
> Out of curiousity, why is there a hard requirement from nodejs directly?

Because usually you don't have to perform an authentication in browser. Now imagine you are in a browser on a SharePoint page. In that case you have already been authenticated. If you need SharePoint (Office 365) authentication from domain other than SharePoint, you need [adal.js](https://github.com/AzureAD/azure-activedirectory-library-for-js)  

May be I don't understand you case fully, can you please tell more details about your requirements?

**Comment by mrozbarry** [comment]
So I'm contracted to work on a platform that offers widgets, one of which uses sharepoint 2013. The platform itself doesn't log a user into sharepoint, and an admin may configure sharepoint 2013 to use adfs. I don't have access to the core of the platform, so I can't implement a server side authentication, and am forced to keep things in-browser. Really, all I need is to get the FedAuth cookie that I can attach to my requests. So far, every sharepoint auth npm package has heavy dependencies for nodejs, and no means to run in the browser.

No problem, though, I'll use a few of these packages (including yours) as reference so I can do it from the browser.

**Comment by s-KaiNet** [comment]
I'm afraid you can't do that because of CORS. ADFS auth requires a few http requests between ADFS server and SharePoint. I haven't tested it in browser, but tend to think this is not possible.

**Comment by mrozbarry** [comment]
The platform I'm using does have a request proxy route that I can pipe requests through, so I think I'm okay in that regard.

**Comment by s-KaiNet** [comment]
Ah in that case it might work. Feel free to ask if there any obstacles.

**Comment by mrozbarry** [comment]
Thanks, I appreciate the help 👍

**Comment by Dragnucs** [comment]
@mrozbarry this is a quit old issue, yet I am interested in knowing if you managed to overcome it. Any tips would be welcome.

My requirement is quit similar. I have an independent Vue.js application that needs to read some data from SharePoint, all in the browser.

I have explored sprestproxy but is tailored for single account usage. I need to preserve permissions for currently logged in user in the application.

Thank you very much.

**Comment by Dragnucs** [comment]
Thank you very much for your quick answer. Maybe I will end up dropping the feature too or resort to a back-end middleware.
