### ISSUE TITLE
New option for logging in? "GetWebLoginClientContext"

### ISSUE THREAD

**Issue by thorild** [s-KaiNet/node-sp-auth#26]
Hi!

I use gulp-spsave and for one on-prem environment I struggle with logging in. I do not have absolute control of the farm so I can't really check the status in terms of logging in mechanisms.

The only way for me to get a clientcontext (csom c#) seems to be by using the OfficeDevPnP.Core component and the AuthenticationManager calling the following method for creating context:

```
AuthenticationManager am = new AuthenticationManager();
 using (var cc = am.GetWebLoginClientContext("https://onpremsite.com"))
 {
  //code
 }
```
This fires up a browser I get signed in automatically (SSO) and then I have my context.

Could this option be added to sp-auth? 

BR

Fredrik

**Comment by s-KaiNet** [comment]
Hi Fredrik,     
this option is out there already, checkout [on-demand](https://github.com/s-KaiNet/node-sp-auth/wiki/On-demand-authentication) wiki article.     

At minimum you need to install `electron` globally:   
`npm install electron -g`  
and provide creds object:  
```
{ 
  ondemand: true
}
```   
However it doesn't work with integrated windows auth, as far as I can recall `GetWebLoginClientContext` also doesn't support integrated windows auth.

**Comment by thorild** [comment]
Awsome!!! Saved my day :+1:  Thanks!
