### ISSUE TITLE
Unexpected XML declaration Error

### ISSUE THREAD

**Issue by sharpart555** [s-KaiNet/node-sp-auth#27]
I got an error when calling spauth.getAuth() with FBA Authencation in SharePoint 2013.

`Unexpected XML declaration. The XML declaration must be the first node in the document, and no white space characters are allowed to appear before it. Line 2, position 5.`

I found that in the file : 
node-sp-auth/lib/src/templates/FbaLoginWsfed.js
on line 3 where the template is declared, there was a space before '<?xml'. 
I got rid of the space between line 3 and 4 (before the '<?xml') and it worked fine.

So I was wondering if you can fix this problem.

Thank you.

**Comment by s-KaiNet** [comment]
Thank you for reporting!   
I've just published fixed 2.3.1 version, so please try it.

**Comment by sharpart555** [comment]
It works great! Thanks!
