### ISSUE TITLE
failing to bundle with webpack

### ISSUE THREAD

**Issue by Perneel** [s-KaiNet/node-sp-auth#28]
I'm using node-sp-auth in a custom library that I made. Now I want to bundle it by using webpack. However I fail to succeed because alot of 'Module not found' errors are being thrown, for example:

`Module not found: Error: Can't resolve 'child_process' in 'C:\Users\user\gitroot\SPRestCallsNTLMTypescript\src\PT_TypeScript\node_modules\cpass\dist\utils'
resolve 'child_process' in 'C:\Users\user\gitroot\SPRestCallsNTLMTypescript\src\PT_TypeScript\node_modules\cpass\dist\utils'
  Parsed request is a module
  using description file: C:\Users\user\gitroot\SPRestCallsNTLMTypescript\src\PT_TypeScript\node_modules\cpass\package.json (relative path: ./dist/utils)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: C:\Users\user\gitroot\SPRestCallsNTLMTypescript\src\PT_TypeScript\node_modules\cpass\package.json (relative path: ./dist/utils)
    resolve as module
      looking for modules in C:\Users\user\gitroot\SPRestCallsNTLMTypescript\src\PT_TypeScript\node_modules
        using description file: C:\Users\user\gitroot\SPRestCallsNTLMTypescript\src\PT_TypeScript\package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: C:\Users\user\gitroot\SPRestCallsNTLMTypescript\src\PT_TypeScript\package.json (relative path: ./node_modules)
          using description file: C:\Users\user\gitroot\SPRestCallsNTLMTypescript\src\PT_TypeScript\package.json (relative path: ./node_modules/child_process)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\user\gitroot\SPRestCallsNTLMTypescript\src\PT_TypeScript\node_modules\child_process doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\user\gitroot\SPRestCallsNTLMTypescript\src\PT_TypeScript\node_modules\child_process.js doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\user\gitroot\SPRestCallsNTLMTypescript\src\PT_TypeScript\node_modules\child_process.json doesn't exist
            as directory
              C:\Users\user\gitroot\SPRestCallsNTLMTypescript\src\PT_TypeScript\node_modules\child_process doesn't exist
[C:\Users\user\gitroot\SPRestCallsNTLMTypescript\src\PT_TypeScript\node_modules\child_process]
[C:\Users\user\gitroot\SPRestCallsNTLMTypescript\src\PT_TypeScript\node_modules\child_process.js]
[C:\Users\user\gitroot\SPRestCallsNTLMTypescript\src\PT_TypeScript\node_modules\child_process.json]
[C:\Users\user\gitroot\SPRestCallsNTLMTypescript\src\PT_TypeScript\node_modules\child_process]
 @ ./node_modules/cpass/dist/utils/machineId.js 3:22-46
 @ ./node_modules/cpass/dist/Cpass.js
 @ ./node_modules/cpass/dist/index.js
 @ ./node_modules/node-sp-auth/lib/src/auth/resolvers/ondemand/OnDemand.js
 @ ./node_modules/node-sp-auth/lib/src/auth/AuthResolverFactory.js
 @ ./node_modules/node-sp-auth/lib/src/index.js
 @ ./NTLM/SPHttpNtlmClient.ts
 @ multi ./NTLM/SPHttpNtlmClient.ts./node_modules/external-editor/main/index.js`

This is also the case for 'tls', 'readline', 'net', 'fs', ... It's like the dependencies aren't bundled. When running(debugging) the code in VS Code, the get and post request work as intended. Any ideas what could be wrong?

### tsconfig
"target": "es5", 
"module": "commonjs",

### webpack
`var path = require("path");
 var config = {
  devtool: "source-map",
  resolve: {
    extensions: [".ts", ".tsx", ".js", ".json"]
  },
  module: {
    loaders: [
      {
        test: /\.tsx?$/,
        loader: "ts-loader",
        exclude: /node_modules/
      }
    ]
  },
};
module.exports = config;`

**Comment by s-KaiNet** [comment]
It's not possible to bundle node-sp-auth to use in browser, because it can be used in nodejs only. That's why you can see a lot of errors.    
You can bundle it with webpack for usage in nodejs, in that case you need to provide valid [`target`](https://webpack.js.org/configuration/target/#target) option (`node` for example, or electron-related when building electron app).

**Comment by sshraki** [comment]
how to bundle it with webpack with right way ??

**Comment by koltyakov** [comment]
We're bundling in the following [way](https://github.com/koltyakov/SPAuthN/blob/master/SPAuthN.Node/webpack.config.js).

The key factor is to provide `target: "node"` as @s-KaiNet pointed out.

Also, I ended up adding:

```json
  module: {
    rules: [{
      test: /rx\.lite\.aggregates\.js/,
      use: 'imports-loader?define=>false'
    }]
  }
```

as my bundles fail without the rule.

But, once again such a bundle script will be for a Node.js environment execution only.

**Comment by sshraki** [comment]
Even after modify bundling still gives this error 

WARNING in ./node_modules/encoding/lib/iconv-loader.js
9:12-34 Critical dependency: the request of a dependency is an expression
    at CommonJsRequireContextDependency.getWarnings (F:\Google Drive\Angular2\Current\ng-app\node_modules\webpack\lib\dependencies\ContextDependency.js:39:18)
    at Compilation.reportDependencyErrorsAndWarnings (F:\Google Drive\Angular2\Current\ng-app\node_modules\webpack\lib\Compilation.js:703:24)
    at Compilation.finish (F:\Google Drive\Angular2\Current\ng-app\node_modules\webpack\lib\Compilation.js:561:9)
    at applyPluginsParallel.err (F:\Google Drive\Angular2\Current\ng-app\node_modules\webpack\lib\Compiler.js:502:17)
    at F:\Google Drive\Angular2\Current\ng-app\node_modules\webpack\node_modules\tapable\lib\Tapable.js:289:11
    at _addModuleChain (F:\Google Drive\Angular2\Current\ng-app\node_modules\webpack\lib\Compilation.js:507:11)
    at processModuleDependencies.err (F:\Google Drive\Angular2\Current\ng-app\node_modules\webpack\lib\Compilation.js:477:14)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
 @ ./node_modules/encoding/lib/iconv-loader.js
 @ ./node_modules/encoding/lib/encoding.js
 @ ./node_modules/node-fetch/lib/body.js
 @ ./node_modules/node-fetch/index.js
 @ ./node_modules/sp-pnp-node/dist/PnpNode.js
 @ ./node_modules/sp-pnp-node/dist/index.js
 @ ./src/app/dataservice.service.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi ./src/main.ts

ERROR in ./node_modules/rx-lite-aggregates/rx.lite.aggregates.js
Module not found: Error: Can't resolve './rx.lite' in 'F:\Google Drive\Angular2\Current\ng-app\node_modules\rx-lite-aggregates'
resolve './rx.lite' in 'F:\Google Drive\Angular2\Current\ng-app\node_modules\rx-lite-aggregates'
  using description file: F:\Google Drive\Angular2\Current\ng-app\node_modules\rx-lite-aggregates\package.json (relative path: .)
  after using description file: F:\Google Drive\Angular2\Current\ng-app\node_modules\rx-lite-aggregates\package.json (relative path: .)
    using description file: F:\Google Drive\Angular2\Current\ng-app\node_modules\rx-lite-aggregates\package.json (relative path: ./rx.lite)
      no extension
        F:\Google Drive\Angular2\Current\ng-app\node_modules\rx-lite-aggregates\rx.lite doesn't exist
      .ts
        F:\Google Drive\Angular2\Current\ng-app\node_modules\rx-lite-aggregates\rx.lite.ts doesn't exist
      .js
        F:\Google Drive\Angular2\Current\ng-app\node_modules\rx-lite-aggregates\rx.lite.js doesn't exist
      as directory
        F:\Google Drive\Angular2\Current\ng-app\node_modules\rx-lite-aggregates\rx.lite doesn't exist
[F:\Google Drive\Angular2\Current\ng-app\node_modules\rx-lite-aggregates\rx.lite]
[F:\Google Drive\Angular2\Current\ng-app\node_modules\rx-lite-aggregates\rx.lite.ts]
[F:\Google Drive\Angular2\Current\ng-app\node_modules\rx-lite-aggregates\rx.lite.js]
[F:\Google Drive\Angular2\Current\ng-app\node_modules\rx-lite-aggregates\rx.lite]
 @ ./node_modules/rx-lite-aggregates/rx.lite.aggregates.js 24:4-26:6
 @ ./node_modules/inquirer/lib/prompts/editor.js
 @ ./node_modules/inquirer/lib/inquirer.js
 @ ./node_modules/node-sp-auth-config/dist/wizards/chooseStrategy.js
 @ ./node_modules/node-sp-auth-config/dist/index.js
 @ ./src/app/getdata.service.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi ./src/main.ts
ERROR in ./node_modules/cpass/dist/utils/machineId.js
Module not found: Error: Can't resolve 'child_process' in 'F:\Google Drive\Angular2\Current\ng-app\node_modules\cpass\dist\utils'
resolve 'child_process' in 'F:\Google Drive\Angular2\Current\ng-app\node_modules\cpass\dist\utils'
  Parsed request is a module
  using description file: F:\Google Drive\Angular2\Current\ng-app\node_modules\cpass\package.json (relative path: ./dist/utils)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: F:\Google Drive\Angular2\Current\ng-app\node_modules\cpass\package.json (relative path: ./dist/utils)
    resolve as module
      F:\Google Drive\Angular2\Current\ng-app\node_modules\cpass\dist\utils\node_modules doesn't exist or is not a directory
      F:\Google Drive\Angular2\Current\ng-app\node_modules\cpass\dist\node_modules doesn't exist or is not a directory
      F:\Google Drive\Angular2\Current\ng-app\node_modules\cpass\node_modules doesn't exist or is not a directory
      F:\Google Drive\Angular2\Current\ng-app\node_modules\node_modules doesn't exist or is not a directory
      F:\Google Drive\Angular2\Current\node_modules doesn't exist or is not a directory
      F:\Google Drive\Angular2\node_modules doesn't exist or is not a directory
      F:\Google Drive\node_modules doesn't exist or is not a directory
      F:\node_modules doesn't exist or is not a directory
      looking for modules in F:\Google Drive\Angular2\Current\ng-app\node_modules
        using description file: F:\Google Drive\Angular2\Current\ng-app\package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: F:\Google Drive\Angular2\Current\ng-app\package.json (relative path: ./node_modules)
          using description file: F:\Google Drive\Angular2\Current\ng-app\package.json (relative path: ./node_modules/child_process)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              F:\Google Drive\Angular2\Current\ng-app\node_modules\child_process doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              F:\Google Drive\Angular2\Current\ng-app\node_modules\child_process.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              F:\Google Drive\Angular2\Current\ng-app\node_modules\child_process.js doesn't exist
            as directory
              F:\Google Drive\Angular2\Current\ng-app\node_modules\child_process doesn't exist
      looking for modules in F:\Google Drive\Angular2\Current\ng-app\node_modules
        using description file: F:\Google Drive\Angular2\Current\ng-app\package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: F:\Google Drive\Angular2\Current\ng-app\package.json (relative path: ./node_modules)
          using description file: F:\Google Drive\Angular2\Current\ng-app\package.json (relative path: ./node_modules/child_process)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              F:\Google Drive\Angular2\Current\ng-app\node_modules\child_process doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              F:\Google Drive\Angular2\Current\ng-app\node_modules\child_process.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              F:\Google Drive\Angular2\Current\ng-app\node_modules\child_process.js doesn't exist
            as directory
              F:\Google Drive\Angular2\Current\ng-app\node_modules\child_process doesn't exist
      looking for modules in F:\Google Drive\Angular2\Current\ng-app\src
        using description file: F:\Google Drive\Angular2\Current\ng-app\package.json (relative path: ./src)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: F:\Google Drive\Angular2\Current\ng-app\package.json (relative path: ./src)
          using description file: F:\Google Drive\Angular2\Current\ng-app\package.json (relative path: ./src/child_process)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              F:\Google Drive\Angular2\Current\ng-app\src\child_process doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              F:\Google Drive\Angular2\Current\ng-app\src\child_process.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              F:\Google Drive\Angular2\Current\ng-app\src\child_process.js doesn't exist
            as directory
              F:\Google Drive\Angular2\Current\ng-app\src\child_process doesn't exist
      looking for modules in F:\Google Drive\Angular2\Current\ng-app\src
        using description file: F:\Google Drive\Angular2\Current\ng-app\package.json (relative path: ./src)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: F:\Google Drive\Angular2\Current\ng-app\package.json (relative path: ./src)
          using description file: F:\Google Drive\Angular2\Current\ng-app\package.json (relative path: ./src/child_process)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              F:\Google Drive\Angular2\Current\ng-app\src\child_process doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              F:\Google Drive\Angular2\Current\ng-app\src\child_process.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              F:\Google Drive\Angular2\Current\ng-app\src\child_process.js doesn't exist
            as directory
              F:\Google Drive\Angular2\Current\ng-app\src\child_process doesn't exist
[F:\Google Drive\Angular2\Current\ng-app\node_modules\cpass\dist\utils\node_modules]
[F:\Google Drive\Angular2\Current\ng-app\node_modules\cpass\dist\node_modules]
[F:\Google Drive\Angular2\Current\ng-app\node_modules\cpass\node_modules]
[F:\Google Drive\Angular2\Current\ng-app\node_modules\node_modules]
[F:\Google Drive\Angular2\Current\node_modules]
[F:\Google Drive\Angular2\node_modules]
[F:\Google Drive\node_modules]
[F:\node_modules]
[F:\Google Drive\Angular2\Current\ng-app\node_modules\child_process]
[F:\Google Drive\Angular2\Current\ng-app\node_modules\child_process.ts]
[F:\Google Drive\Angular2\Current\ng-app\node_modules\child_process.js]

**Comment by s-KaiNet** [comment]
@sshraki which kind of application are you building? Angular app? In that case, as Andrew and I pointed out, it's not possible to use `node-sp-auth` in browser-based app.

**Comment by sshraki** [comment]
yes angular app so what is the best way to get data from SharePoint with angular ??

**Comment by s-KaiNet** [comment]
There is a special project for that purpose - [sp-rest-proxy](https://github.com/koltyakov/sp-rest-proxy/). It spawn local web server running on nodejs and routes http requests from localhost to your real SharePoint.

**Comment by koltyakov** [comment]
Here is a decent [blog post](http://johnliu.net/blog/2017/9/angular-4-sharepoint-on-premises-localhost-development-and-sp-rest-proxy) how to integrate the proxy into Angular toolchain.

**Comment by s-KaiNet** [comment]
Closing as seems not an issue.
