### ISSUE TITLE
Sharepoint Online Auth

### ISSUE THREAD

**Issue by Aymkdn** [s-KaiNet/node-sp-auth#29]
Hello,

I'm trying to auth against our Sharepoint Online. I'm not sure which authentication method is used by my organization (I think it's ADFS).

When I try to go to our Sharepoint, I'm redirected to https://login.microsoftonline.com/ where I enter my work email address and then it automatically logs me in (going thru our SSO portal and then to microsoftonline.com/login.srf)

When I try `sp-auth` to connect with option `ondemand:true` it works: the browser window shows up and I can log in.

However if I try `{username, password}` ([as described here](https://github.com/s-KaiNet/node-sp-auth/wiki/SharePoint%20Online%20user%20credentials%20authentication)) it doesn't work:
```javascript
const spauth = require('node-sp-auth');
const request = require('request-promise');

spauth
  .getAuth('https://tenant.sharepoint.com/sites/dev/', {
    username:"username@tenant.onmicrosoft.com",
    password:"p@ssword"
  })
  .then(data => {
    console.log(data)
    let headers = data.headers;
    headers['Accept'] = 'application/json;odata=verbose';

    request.get({
      url: 'https://dell.sharepoint.com/sites/educate/_api/web',
      headers: headers,
      json: true,
      rejectUnauthorized: false
    }).then(response => {
      console.log(response.d.Title);
    });
  });
```
It returns:
```
Unhandled rejection Error: <S:Fault>
  <S:Code>
    <S:Value>S:Sender</S:Value>
    <S:Subcode>
      <S:Value>wst:FailedAuthentication</S:Value>
    </S:Subcode>
  </S:Code>
  <S:Reason>
    <S:Text xml:lang="en-US">Authentication Failure</S:Text>
  </S:Reason>
  <S:Detail>
    <psf:error>
      <psf:value>0x80048821</psf:value>
      <psf:internalerror>
        <psf:code>0x80041012</psf:code>
        <psf:text>The entered and stored passwords do not match.</psf:text>
      </psf:internalerror>
    </psf:error>
  </S:Detail>
</S:Fault>
    at OnlineUserCredentials.postToken (C:\path\node_modules\node-sp-auth\lib\src\auth\resolvers\OnlineUserCredentials.js:149:19)
```

I also tried other credentials ([as described here](https://github.com/s-KaiNet/node-sp-auth/wiki/ADFS%20user%20credentials%20authentication)):
```javascript
spauth
  .getAuth('https://tenant.sharepoint.com/sites/dev/', {
    username:"username@tenant.com",
    password:"p@ssword"
  })
```
This time it returns:
```
Unhandled rejection TypeError: Cannot read property 'firstChild' of undefined
    at request.post.then.xmlResponse (C:\path\node_modules\node-sp-auth\lib\src\utils\AdfsHelper.js:29:67)
```

We don't have two factors authentication, and I tried to create an [Online App Addin](https://github.com/s-KaiNet/node-sp-auth/wiki/SharePoint%20Online%20addin%20only%20authentication) but I get a `An unexpected error has occurred.` from `appregnew.aspx`...

Any idea what I'm doing wrong?

My final purpose is to create a script that will automatically grab some data from Sharepoint Online every week at a specific time (so the `ondemand` is not a solution because I won't be behind the keyboard when the script will run).

Thanks :-)

**Comment by koltyakov** [comment]
Hey @Aymkdn,

I'm wondering, did you see [this page](https://github.com/s-KaiNet/node-sp-auth/wiki/ADFS-user-credentials-authentication) with ADFS details?
Some additional parameters should be provided for ADFS for successful authentication.

> The entered and stored passwords do not match.
Usually appears when there is a typo in username/password.
But I suspect that it's really the ADFS case and you just missing `relyingParty` and `adfsUrl` in creds configuration.

**Comment by Aymkdn** [comment]
Do you know how to find the relyingParty and adsfUrl?

I'm off for tonight, so I'll investigate that option tomorrow. Thank you!

**Comment by koltyakov** [comment]
When logging in in UI a user is redirected to ADFS page. I would try taking this URL part.

`relyingParty` can be reconfigured with ADFS admin to be any string. I would try default one `urn:sharepoint:portal` first, then if wrong would ask an admin to say it or try `Get-SPTrustedIdentityTokenIssuer` (as described in the article).

Strange that you're are getting error while trying regestering add-in.

**Comment by s-KaiNet** [comment]
I believe the only reason for the error is that you\your company uses third party ADFS provider. For example PingIdentiy. Can you check it somehow?      
Can you please also put a `console.log(xmlResponse);` at line 30, right before `let doc = new xmldoc.XmlDocument(xmlResponse);`

**Comment by s-KaiNet** [comment]
BTW add-in only auth should work any way for SharePoint Online. If you see an error, please make sure that you are not requesting tenant scoped permissions from regular site collection, it's allowed only from admin site collection.     
For example, if you are on `https://contoso.sharepoint.com/sites/dev/_layouts/15/appregnew.aspx`, then you can request maximum below permissions:   
```xml
<AppPermissionRequests AllowAppOnlyPolicy="true">
  <AppPermissionRequest Scope="http://sharepoint/content/sitecollection" Right="FullControl" />
</AppPermissionRequests>
```  
However from admin site collection, i.e. `https://[organizaiton]-admin.sharepoint.com/_layouts/15/appinv.aspx` you can request tenant scoped permissions:  
```xml
<AppPermissionRequests AllowAppOnlyPolicy="true">
  <AppPermissionRequest Scope="http://sharepoint/content/tenant" Right="FullControl" />
</AppPermissionRequests>
```

**Comment by Aymkdn** [comment]
Thanks for your comments!

I've finally been able to add an app and use the Addin solution (when I used exactly the same information that you provide in your example, then it worked... I think it's due to the "App Domain" that might require to be "localhost" ?). So I guess I can use this solution.

I wanted to try again with `adfsUrl` and `relyingParty`. So I checked our SSO redirection page and there is a logo "Ping Identity" there (and the server name is `pf` that may mean "PingFederate"). So I added the `console.log(xmlResponse)` as you told me, and here is the result : 
```html
<!DOCTYPE html>
<!-- template name: http.error.page.template.html -->
<html lang="en" dir="ltr">
<head>
    <title>Error</title>
    <base href="https://the_adfs_url_I_tried/" />
    <meta name="robots" content="noindex, nofollow" />
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="viewport" content="initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <link rel="stylesheet" type="text/css" href="assets/css/main.css" />
</head>

<body>
<div class="ping-container">
    <div class="ping-header">
        Error
    </div><!-- .ping-header -->
    <div class="ping-body-container">
        <div class="section-title">
            Oops
        </div>
        <div class="ping-messages ping-nopad">
            <div>
                Looks like something is not right. Please contact your administrator.
            </div>
            <div class="ping-note-text">
                404 - Not Found
            </div>
        </div>
    </div> <!-- .ping-body-container -->
    <div class="ping-footer-container">
        <div class="ping-footer">
            <div class="ping-credits">
                <a href="http://www.pingidentity.com">PingIdentity</a>
            </div>
        </div> <!-- .ping-footer -->
    </div> <!-- .ping-footer-container -->
</div> <!-- .ping-container -->
</body>
</html>
```

I'm not sure why it says **404 - Not Found** here :thinking:

**Comment by s-KaiNet** [comment]
PingIdentity means third party SSO provider which is not supported. It sends different response and it's difficult to analyze and adapt library to support it. That's why add-in only auth is the only way to go for you.     
So I'm closing as it seems to be resolved.   
Feel free to reopen or fire another issue if anything goes wrong :)
