### ISSUE TITLE
Could it be possible to authenticate a browser using saved authentication data?

### ISSUE THREAD

**Issue by tavikukko** [s-KaiNet/node-sp-auth#36]
When using ondemand option, the authentication data is saved in disk, so could it be possible to open a SharePoint Online site in browser using the saved authentication data, without existing auth cookies in the browser? For example opening browser from electron app without the need to re-authenticate?

**Comment by s-KaiNet** [comment]
In theory yes, it's possible, however what's the use case? What kind of issue you're trying to fix?

**Comment by koltyakov** [comment]
My guess is the desktop app with portal elements as web views inside.

**Comment by tavikukko** [comment]
In a mobile app, created with cordova/ionic. Its easy to access the _api using access token, and that access token you can save easily in mobile app, but then if you want to see the actual site using inappbrowser, it would be handy to reuse the saved token to reauthneticate the inabbbrowser. @koltyakov was quite close :)

**Comment by tavikukko** [comment]
The problem comes when you close the app and and reopen it, the inappbrowser cookies will be cleared. But if there is a way to reuse the existing cached authentication data, and you could reauthentica the inappbrowser during app start. This would also allow to have multiple accounts stored in the apps persisted cache, meaning that you could switch account on the fly, to access other SPO sites without the need to re authenticate, ofcourse meaning that the cached authentication data is not yet expired. In that case a new interactive authentication flow would be created.

**Comment by tavikukko** [comment]
But like @koltyakov mentioned, I also have interest to build a electron app, that would display SharePoint webview. To test this scenario, I will create now a simple electron project to test how node-sp-auth plays with it and study how cookies are handled. In cordova app, if you use inappbrowser, you can actually run external javascript in it when its opened. So, in theory you could open inappbrowser and execute script that creates post request with valid payload to authentication to get the auth cookies to  the browser?

**Comment by koltyakov** [comment]
I consider it's possible defining cookies from backend Electron process with [Cookies API](https://github.com/electron/electron/blob/master/docs/api/cookies.md).

**Comment by s-KaiNet** [comment]
I'm not aware of Cordova, Ionic and all this stuff about.. so probably in that regard my help might be useless. Any way let me try to describe how it works in nodejs and what potential issues you might have in inappbrowser.     

node-sp-auth doesn't work in browser, primary because of CORS. It sends requests to some online services which don't support CORS. That's why I have some doubts if its' possible to run script and successfully send requests to those http services from inappbrowser.    

From electron perspective, it relatively simple to open any website in an electron window, set any cookie, execute any script, etc. It's like controlling Google Chrome with elevated privileges :) Electron has rich API (like one of @koltyakov mentioned, cookies)

**Comment by s-KaiNet** [comment]
> I also have interest to build a electron app, that would display SharePoint webview        

I'm curious, if it's work-related or a new amazing open source tool? :)

**Comment by tavikukko** [comment]
@s-KaiNet I think Chrome Browser will change the possibilities of extensions (eg. executing js for example) in the near future, meaning that SP Editor will not be able to function anymore. So I have starter to look for alternative possibilities, where electron app with web view is one of them.

**Comment by s-KaiNet** [comment]
> Chrome Browser will change the possibilities of extensions (eg. executing js for example) in the near future, meaning that SP Editor will not be able to function anymore   

wow, that's not good. I'm also aware that Chrome removes "Chrome apps" in current or next decade (may be that's related), making postman chrome app useless. From the other side, there is a postman desktop app, which is not so cool in handling cookies.

**Comment by tavikukko** [comment]
In Ionic, you can send request using background process, so the CORS will not be a problem. The only problem what see with Ionic and InAppBrowser, it to set the cookies. You can set cookies using injected javascript, but not with httpOnly flag, which I think is necessary the cookies actually to be valid?

**Comment by s-KaiNet** [comment]
Yes, probably you have to set httpOnly as well. However who knows how it works in InAppBrowser. You can give it a try, you need FedAuth and rtFa cookies to be set, you can even copy them from Chrome dev tools.

**Comment by tavikukko** [comment]
In node-sp-auth, I'm wondering how the tokens are refreshed in electron using ondemand + persist option set to true? is interactive flow necessary when tokens expire?

**Comment by s-KaiNet** [comment]
Yes, interactive flow is necessary in that case.

**Comment by tavikukko** [comment]
Cool, thanks guys, always a pleasure! I will continue my research.

**Comment by koltyakov** [comment]
@tavikukko, just created an Electron sample with node-sp-auth integration. A couple of testing and will push it to a repo.

**Comment by koltyakov** [comment]
Here it [is](https://github.com/koltyakov/sp-auth-electron-sample).

**Comment by koltyakov** [comment]
Added authentication for HTML On-Prem case via Electron app `login` event.

**Comment by tavikukko** [comment]
Man you really got in to this :) I'm checking the possibilities of NativeScript + webview + cookies.
