### ISSUE TITLE
Support for Office 365 Dedicated

### ISSUE THREAD

**Issue by cebud** [s-KaiNet/node-sp-auth#39]
Hi,
after upgrade from version 2.3.4 to 2.4.0 i'm receiving exception 'Unable to resolve hosting environment. Site url:...'. In previous 2.3.4 it was working correctly. 

We are using **IOnlineAddinCredentials** as auth option.  Our company have '**Office 365 Dedicated**' environment on **custom domain** (host is not ending by sharepoint.com). 

Our AcsRealmUrl is same as for hosting environment Production.

Determine whether environment is Online, is not possible by checking host that end with 'sharepoint.com,...', because Office 365 Dedicated environment are hosted on custom domains.

Maybe solution is not throw exception in method ResolveHostingEnvironment and return default hosting environment Production or possibility to configure host for Online environment in configuration options.

Thank you,
Martin Dubec

**Comment by s-KaiNet** [comment]
TBH I don't quite understand how previous version works for you, because if
the url doesn't ends with .sharepoint, it explicitly selects onprem path.
In that case authenticating will fail.

**Comment by salascz** [comment]
Hi,
thats a common misunderstanding, that authors detect Office 365 based on ".sharepoint" in url. Dedicated Office 365 environments are not onprem instances, may be hosted on custom domain and in dedicated space in Microsoft cloud. This solution is used by large companies with significant number of users.  

Best Regards,
Jiri

**Comment by cebud** [comment]
@s-KaiNet 
It is working for version 2.3.4. There are test results from your integration tests:
  node-sp-auth: integration - online addin only
    ✓ should get list title with core http(s) (19996ms)
    ✓ should get list title (1172ms)
    ✓ should get Title field (1192ms)
  3 passing (22s)

**Comment by koltyakov** [comment]
Thank you guys,

I think we found out (with @s-KaiNet) what causes this issue and what changes became breaking for O365 Dedicated.
Please stick with version 2.3.4 for a while. Before the fix is delivered.

Could you please confirm that you use(d) Add-In Only auth? SAML never worked or was required in this case with O365 Dedicated, didn't it?

Will it be possible that you tried cloned from a feature branch version (we'll let you know after the fix with instructions)? So we can be sure that next version would work before publishing it in NPM. Because without such environment it would be a blind fixing without actual integration testing.

**Comment by cebud** [comment]
Thank you for the help. 

Yes, we've set fixed version for node-sp-auth to 2.3.4.

I confirm, that we are using only **Online Add-In** auth.

It's no problem to try it from feature branch, it's easy and quick check for me, so let me know after the fix will be ready to test in your branch.

**Comment by koltyakov** [comment]
Could you please check if this works for you? https://github.com/koltyakov/node-sp-auth/tree/dev-o365dedicated-addinonly-fix

Just one line change to return `HostingEnvironment.Production` but not an exception if the env URL is not indexed in `.sharepoint.*` list.

Will think how to do it in a more elegant way after Sergei is back from traveling.

**Comment by koltyakov** [comment]
The simplest way to test:

- `git clone https://github.com/koltyakov/node-sp-auth && cd node-sp-auth`
- `git checkout dev-o365dedicated-addinonly-fix`
- `npm install`
- create a test runner, i.e. `./demo/addinonly.ts` with:

```typescript
import * as spauth from '../src';

spauth
  .getAuth('[O365_Dedicated_siteUrl]', {
    clientId: '[clientId]',
    clientSecret: '[clientSecret]'
  })
  .then(data => {
    console.log(data.headers);
  });
```
- run with ts-node (should be globally installed) `ts-node ./demo/addinonly.ts`

On success, cookies should be printed out.

**Comment by cebud** [comment]
Great job, it is working. Integration tests are passing:

integration - online addin only
    ✓ should get list title with core http(s) (4698ms)
    ✓ should get list title (1206ms)
    ✓ should get Title field (1137ms)
  3 passing (7s)

Thank you

**Comment by koltyakov** [comment]
Nice! Thanks for the feedback, Martin! I've PRed the fix. 
AFAIK, Sergei is coming back at the end of the next week. Please stick with the previously published version or cloned feature branch until then. Yet, knowing that the fix works for O365 Dedicated is definitely a good thing.

**Comment by s-KaiNet** [comment]
Thank you guys, and at the same time sorry for breaking you. I've merged changes and new fixed version is available in npm. Please try it.
