### ISSUE TITLE
Need Support for Custom FedAuth Cookie Name

### ISSUE THREAD

**Issue by renzska** [s-KaiNet/node-sp-auth#4]
We have multiple environments that have modified FedAuth cookie names, such as FedAuth01, FedAuth02, FedAuthSPXVT01, etc. Because of this, node-sp-auth and subsequently, spsave and gulp-spsave do not work. I need to be able to set the FedAuth Cookie Header Name. I have tested this by manually modifying the AdfsCredentials.js directly:

```
var authCookie = consts.FedAuth + '=' + cookie.parse(response.headers['set-cookie'][0])[consts.FedAuth];
```

and setting the consts.FedAuth to my custom "FedAuth01" cookie header name. This has fixed my issue, but it of course is not a fix in the codebase.

I will look into forking your repo and doing a pull request to make this a part of this solution. Would there need to be modifications done to spsave and gulp-spsave once this pull request is completed?

Thanks,

John

**Comment by s-KaiNet** [comment]
Hi, 
can you please add custom cookie name as additional optional parameter for `IAdfsUserCredentials`?   
Then ADFS credentials will look like:  

```
{
  username: 'johnsmith@contoso-corp.com',
  password: 'sd46$fFF$',
  relyingParty: 'urn:sharepoint:portal',
  adfsUrl: 'https://adfs3',
  adfsCookie: 'FedAuth01'
}
```  
By doing this no changes will be required for `spsave` or `gulp-spsave`, you will simply add one additional param credentials object with your adfs cookie name.   
Does that sound good?
