### ISSUE TITLE
ondemand + force on macos not working

### ISSUE THREAD

**Issue by tavikukko** [s-KaiNet/node-sp-auth#43]
In a simple electron app ( running on macOS, on windows it is working), where using node-sp-auth to authenticate with ondemand:true + force:true settings, the auth window does not get closed (propably fails internally). I found the issue using [this](https://github.com/koltyakov/sp-auth-electron-sample/issues/1) sample and also reported it as a issue there.

**Comment by s-KaiNet** [comment]
That's an interesting one... I will try to take a look at this one at the end of the week. When `forse:false`, does it work?

**Comment by tavikukko** [comment]
yes, force: false works. With force: true it hides the window but does not close it and hangs. Manually closing the pop-up window the program continues to run. It seems to fail in saveAuthData method.

**Comment by s-KaiNet** [comment]
Hi Tomi,  
how critical this issue for you? Unfortunately, I still haven't found time to dig into it. If it's a blocker for your chrome add-in experiments or anything else, please indicate that in comments.

**Comment by tavikukko** [comment]
Not critical at all, I was just testing and realised this issue.

**Comment by s-KaiNet** [comment]
Finally I have found a time to test it properly on osx. I don't have a "real" osx, so had to use virtual machine. It appeared that the cause is the window not closing properly and instead staying in the menu bar.    

Now it works fine for me, please reopen if you still have issues.
