### ISSUE TITLE
Tsconfig.json throwing error

### ISSUE THREAD

**Issue by MattGarnettWelsh** [s-KaiNet/node-sp-auth#44]
My linter is picking up this error in your package:

`[ts] No inputs were found in config file '_path_/node_modules/node-sp-auth/tsconfig.json'. Specified 'include' paths were '["src/**/*.ts","test/**/*.ts"]' and 'exclude' paths were '["./lib"]'.`

Installed via npm.

Best Regards,
Matt.

**Comment by s-KaiNet** [comment]
Hi, your linter shouldn't analyze anything inside node_modules folder, that's why I think the error is not relevant here.    
Please feel free to reopen.
