### ISSUE TITLE
Error trying to authenticate to SharePoint Online

### ISSUE THREAD

**Issue by ushroff79** [s-KaiNet/node-sp-auth#49]
we have multi-factor authentication with ADFS. getting error The sign-in name or password does not match one in the Microsoft account system.

var username = "xx@company.com";
            var password = "xxxxx";
            var endPoint = "https://company.sharepoint.com/sites/SPDeveloper";
            var stsEndpoint = "https://login.microsoftonline.com/extSTS.srf";
            var signInUrl = "https://company.sharepoint.com/_forms/default.aspx?wa=wsignin1.0";
            var browserHost = "company.sharepoint.com"; //e.g. mycompany.sharepoint.com 
            var browserUserAgent = "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36";

            var cookies = new CookieContainer();
            var executingPath = Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location);
            var payLoadSts = System.IO.File.ReadAllText(Path.Combine(executingPath, "extStsTemplate.xml")).Replace("{USERNAME}", username).Replace("{PASSWORD}", password).Replace("{ENDPOINTREFERENCE}", endPoint);
         
            //var payLoadSts = SMAL.Replace("{USERNAME}", username).Replace("{PASSWORD}", password).Replace("{ENDPOINTREFERENCE}", endPoint);

            // webrequest 0 
            // webrequest 0: get the RpsContextCookie 
            // webrequest 0 
            string requiredAuthUrl = string.Format("{0}/_layouts/15/Authenticate.aspx?Source={1}", endPoint, HttpUtility.UrlDecode(endPoint));
            HttpWebRequest request0 = (HttpWebRequest)WebRequest.Create(requiredAuthUrl);
            request0.Accept = "*/*";
            request0.Headers.Set(HttpRequestHeader.AcceptLanguage, "en-US");
            request0.Headers.Set(HttpRequestHeader.AcceptEncoding, "gzip, deflate");
            request0.UserAgent = browserUserAgent;
            request0.AllowAutoRedirect = false;
            request0.CookieContainer = cookies;

            var response0 = (HttpWebResponse)request0.GetResponse();

            // webrequest 1
            // webrequest 1: login
            // webrequest 1
            var request1 = (HttpWebRequest)WebRequest.Create(stsEndpoint);
            request1.CookieContainer = cookies;
            var data = Encoding.ASCII.GetBytes(payLoadSts);

            request1.Method = "POST";
            request1.ContentType = "application/xml";
            request1.ContentLength = data.Length;

            using (var stream1 = request1.GetRequestStream())
            {
                stream1.Write(data, 0, data.Length);
            }

            // Response 1
            var response1 = (HttpWebResponse)request1.GetResponse();
            var responseString = new StreamReader(response1.GetResponseStream()).ReadToEnd();

            // Get BinarySecurityToken
            var xData = XDocument.Parse(responseString);
            var namespaceManager = new XmlNamespaceManager(new NameTable());
            namespaceManager.AddNamespace("S", "http://www.w3.org/2003/05/soap-envelope");
            namespaceManager.AddNamespace("wst", "http://schemas.xmlsoap.org/ws/2005/02/trust");
            namespaceManager.AddNamespace("wsse", "http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd");
            var BinarySecurityToken = xData.XPathSelectElement("/S:Envelope/S:Body/wst:RequestSecurityTokenResponse/wst:RequestedSecurityToken/wsse:BinarySecurityToken", namespaceManager);

**Comment by s-KaiNet** [comment]
As I mentioned in another thread you posted, 
> For .net I recommend you to use [PnP .NET Component](https://github.com/SharePoint/PnP-Sites-Core) with [Authentication Manager](https://dev.office.com/blogs/Introduction-to-authentication-manager-in-pnp-core-library) from there.   

Authentication Manager contains various methods for obtaining authenticated ClientContext, including ADFS.    
I'm going to close this one, because it isn't related to node-sp-auth. If you have any issues related to the library, please feel free to reopen and describe your issue.
