### ISSUE TITLE
Update node-sp-auth to latest version

### ISSUE THREAD

**Issue by njosefbeck** [s-KaiNet/node-sp-auth#50]
Hello!

My app uses the NPM package `gulp-spsave`. When I installed the package, NPM audit showed me there were some [vulnerabilities](https://nodesecurity.io/advisories/566) related to the `hoek` NPM package. The dependency tree looked like: 

```
gulp-spsave > spsave > sp-request > node-sp-auth > jsonwebtoken > joi > topo > hoek
```

After doing investigating, and realizing that `hoek` fixed the vulnerability in their latest release (5.0.3), I traveled up the chain. `topo` uses the latest release of `hoek`, and `joi` uses the latest release of `topo`. The latest release of `jsonwebtoken` (8.3.0) doesn't use `joi` at all. The version of `jsonwebtoken` that you use in your code is `7.4.3`, which contains an old version of `joi` (6.10.1).

If you wouldn't mind updating your version of `jsonwebtoken` to the latest one, that would be helpful for resolving these vulnerabilities. Additionally, you might see about updating the other packages in your library, as they might also be affected by vulnerabilities that were patched in later versions.

Thanks!

**Comment by s-KaiNet** [comment]
Hi Nathan, thank you for reporting!. I've just updated the package with update version of `jsonwebtoken` package.
