### ISSUE TITLE
does it support multiple authentication provider?

### ISSUE THREAD

**Issue by kishore-indraganti** [s-KaiNet/node-sp-auth#54]
Let's say the website which I am trying to authenticate has multiple authentication methods (SAML and Windows authentication), I want to get authorize using windows authentication method? How to do that? On providing the credentials directly under user credentials not working.

**Comment by s-KaiNet** [comment]
Which type of windows authentication do you use?   
 - NTLM v1
 - NTLM v2
 - Kerberos ?

**Comment by kishore-indraganti** [comment]
NTLM v2

**Comment by s-KaiNet** [comment]
In that case I suggest you to try different combinations of credentials (all of them are supported by node-sp-auth):  
```
username: 'your username without domain, i.e. john_smith',
password: 'pswd',
domain: 'your domain, i.e. contoso, not contoso.com'
```
or
```
username: 'your username with domain, i.e. contoso\\john_smith',
password: 'pswd'
```
or 
```
username: 'your user logon name, i.e. john_smith@contoso.com',
password: 'pswd'
```

Please check if anything from above works for you.    

If nothing works, the last option you can try is to extend your SharePoint web application to a web application with NTLM authentication only and use it for node-sp-auth related tasks.

**Comment by kishore-indraganti** [comment]
Sure, I will try it and let you know. I will close this issue. thanks for your support.

**Comment by koltyakov** [comment]
@kishore-indraganti, found the doc article for the case - https://docs.microsoft.com/en-us/previous-versions/office/developer/sharepoint-2010/hh124553(v%3Doffice.14).
Copying the solution which helped us with the case: adding `"X-FORMS_BASED_AUTH_ACCEPTED": "f"` header to the requests do the job.

**Comment by kishore-indraganti** [comment]
@koltyakov thanks a million, It worked with your suggestion, attaching sample code for reference.

`const { AuthConfig } = require('node-sp-auth-config');
const { PnpNode } = require('sp-pnp-node');
const { sp, Web } = require('@pnp/sp');

new AuthConfig().getContext().then(context => {

  sp.setup({
    sp: {
      fetchClientFactory: () => new PnpNode(context),
      headers: {
        accept: 'application/json;odata=verbose',
        'x-forms_based_auth_accepted': 'f'
      }
    }
  });

  const web = new Web(context.siteUrl);
  return web.select('Title').get().then(({ Title }) => console.log(Title));

}).catch(console.log);`
