### ISSUE TITLE
Custom Domain Name for SharePoint Online - Override the default auth resolver

### ISSUE THREAD

**Issue by larnera** [s-KaiNet/node-sp-auth#56]
Hi. We use a custom domain name for SharePoint Online which means the auth resolver thinks the SharePoint environment we're using is on premise and not SP Online. 

We can get around this by setting the below in AuthResolverFactory.js : 

`  if (authOptions.isUserCredentialsOnpremise(siteUrl, options)) {
            return new OnlineUserCredentials_1.OnlineUserCredentials(siteUrl, options);
        }`

I was wondering though, is this something you can add into the next release, maybe set a flag in the options which allows us to override the auto auth resolver? 

Many thanks, Adam

**Comment by s-KaiNet** [comment]
Hi, 
good point. Strangely enough, that this bug was revealed only today. Looks like custom domains for Online is a fairly rare feature, isn't it?   

I will release an update later this week.

**Comment by larnera** [comment]
Many thanks @s-KaiNet.  Yep, it's pretty rare from what I can gather.  I can't find much online about custom domains for SharePoint Online so maybe it's a new thing MS have enabled - we moved to O365 just last week. 

Much appreciated. Cheers.

**Comment by s-KaiNet** [comment]
Now you can explicitly add `online: true` to your credentials. In that case it resolves Online auth provider and works according to your needs.   

I'm closing it for now, please reopen if there are still any issue.

**Comment by larnera** [comment]
This is brilliant! Thanks for doing this and making the change so quickly.
