### ISSUE TITLE
"Unable to resolve namespace authentiation type. Type received: Unknown"

### ISSUE THREAD

**Issue by wmertens** [s-KaiNet/node-sp-auth#57]
I'm trying to connect to what I think is an onprem host, with NTLM credentials.

It fails with the above error message, the response it gets indeed has the string `"Unknown"`.

Not sure how to proceed.

**Comment by wmertens** [comment]
The URL was wrong 🙄

**Comment by sanjeev2315** [comment]
@wmertens - Hey, I am getting the same error exactly, can you please explain what fix you did in URL

**Comment by wmertens** [comment]
You need to make sure that the url you connect to works, and if you add /_api/web to it you get a response. Then you can use it.

**Comment by sanjeev2315** [comment]
Hey, thanks for the info, so do i need to append _api/web at then end of the url. So to be more specific if i add _api/web to my site url, it returns me response on browser but if i append _api/web at the end of full url(site url+ file location) it says 404. I am not sure what is wrong

**Comment by wmertens** [comment]
You need to use the url that works when you add _api to it. Don't add anything. Then use the api to work with the filenames etc

**Comment by vishal9890** [comment]
Please open this issue again as this did not resolved even after i provided correct URL.

**Comment by publicvirtualvoid** [comment]
I'm also seeing this error despite /_api/web giving a seemingly valid response.

**Comment by publicvirtualvoid** [comment]
Update: you also get this error if you don't format the username properly

**Comment by russoedu** [comment]
In my case, I was just using the "username", after adding the "@" and the whole email it worked.
