### ISSUE TITLE
Authenticating with the user context?

### ISSUE THREAD

**Issue by simkessy** [s-KaiNet/node-sp-auth#61]
Hey, I'm using gulp and spsave to push files to SharePoint. I'm wondering if it's possible to authenticate using the logged in windows user account which has access to sharepoint instead of providing a user name and password?

**Comment by s-KaiNet** [comment]
Hi, that would be a good option, however, I have never seen anything similar to .NET "DefaultNetworkCredentials" in nodejs. I believe .NET uses some low-level API and it's hard to replicate it in node. Thus I can't help here.    
Please feel free to reopen if you have any good thoughts or suggestions on this.
