### ISSUE TITLE
Pass timeout to request

### ISSUE THREAD

**Issue by wmertens** [s-KaiNet/node-sp-auth#65]
I'm having issues with a client, they have an on-prem server and for some reason packets are lost.

This causes authentication to hang. I implemented a retry mechanism, but the OnPremiseUserCredentials resolver doesn't provide a `timeout` value to `request`, so it hangs forever.

Can you add `timeout: 30000` to the request calls? That should be sufficient, right?

**Comment by s-KaiNet** [comment]
Hi @wmertens 	
Sorry for the late reply, vacation things...   

You can try below trick with request configuration:   

```typescript
import * as spauth from 'node-sp-auth';

spauth.setup({
        requestOptions: {
          timeout: 30000
        }
 });
```

**Comment by wmertens** [comment]
Ah, thank you, I didn't find that, I worked around it by monkeypatching
fetch :)

Wout.

**Comment by s-KaiNet** [comment]
Ok :) Then I'm closing this one.
