### ISSUE TITLE
"UNAUTHORIZED" when posting to REST API via App only ID

### ISSUE THREAD

**Issue by vaderj** [s-KaiNet/node-sp-auth#68]
I am using Node.js v8.16.1

 I am trying to create a list item on a list.  I am able to query the list just fine using the following function :

`
async function querySPlist(){
    return new Promise((resolve, reject) => {
        spauth.getAuth(siteUrl, {
            clientId: clientId,
            clientSecret: clientSecret
        }).then(function (data) { 
            request.get({
                url: siteUrl + "/_api/web/lists/getbytitle('" + listName + "')/items?$select=*",
                headers: {
                    'Accept': 'application/json;odata=verbose',
                    "content-type":"application/json;odata=verbose",
                    'odata-version': '',
                    'Authorization' :  data.headers.Authorization
                },
                json: true
            })
        .then(function (listData) {
                resolve(listData);
            });
        });
    });
}
`

and calling it:

`var listResponse = await querySPlist()`

I am also able to retrieve the request digest (even though documentation states I should not need it via app authentication)

When I attempt to create a new list item with the following function, however, the only response I can get is "401 UNAUTHORIZED"

`
async function createSPListItem(requestDigest){
    return new Promise((resolve, reject) => {
        var authResp ;
        spauth.getAuth(siteUrl, {        
            clientId: clientId,
            clientSecret: clientSecret
        }).then(function (respData) { 
            
            let newItem ={
                "__metadata": { "type": "SP.Data.SiteProvListItem" },                
                "Title" : "Title"
            }
            request.post({
                url: siteUrl + "/api/web/lists/getbytitle('" + listName + "')/items",
                body: newItem,
                headers: {
                    'Accept': 'application/json;odata=verbose',
                    "content-type":"application/json;odata=verbose",
                    'odata-version': '',
                    'Authorization' :  respData.headers.Authorization,
                    "X-RequestDigest": requestDigest,
                    "IF-MATCH": "*"
                },
                json: true
            }).then(function (listData) {
                resolve(listData);
            });
        });
    });
}`

App permissions request XML: 

`                <AppPermissionRequests AllowAppOnlyPolicy="true">
                <AppPermissionRequest Scope="http://sharepoint/content/sitecollection/web/list" Right="Write" />
                </AppPermissionRequests`

Am I screwing this up somewhere?

**Comment by vaderj** [comment]
I used the same params as a function with jQuery and it worked, so I instead moved on to use to using the PnP library which works fine.  It seems there is some sort of auth issue when attempting to post node-sp-auth

**Comment by s-KaiNet** [comment]
If you're working with SharePoint REST API from nodejs, I would recommend using [pnpjs](https://github.com/pnp/pnpjs) together with [pnp-auth](https://github.com/SharePoint-NodeJS/pnp-auth) authentication. It abstracts a lot of authentication things away.
