### ISSUE TITLE
Two-Factor Authentication plans?

### ISSUE THREAD

**Issue by Js-Brecht** [s-KaiNet/node-sp-auth#69]
I was just wondering if there were any plans on supporting two-factor authentication.  Not that I'm opposed to using add-in credentials, and the sort.

I mostly just use `node-sp-auth` for dev purposes, anyway.  Anytime I have an app in production, it's either a server-side app that uses add-in credentials anyway, or it's a front-end GUI that makes it much easier to execute the two-factor auth flow...  That last bit would be the tricky part, I'd think, using node.

I'm asking purely out of curiosity.

**Comment by s-KaiNet** [comment]
I don't have plans to support 2fa, there is a workaround though. You can generate an [app password](https://support.office.com/en-us/article/create-an-app-password-for-office-365-3e7c860f-bda4-4441-a618-b53953ee1183) and use instead of a real password in user credentials scenario.

**Comment by Js-Brecht** [comment]
Fair enough.  Closing this issue.
