### ISSUE TITLE
error:invalid_client, Invalid audience Uri for Onpremise Addin Only authentication

### ISSUE THREAD

**Issue by raghuureddy** [s-KaiNet/node-sp-auth#7]
We have our dev servers SP sites with hostname & port number. I see a bug here & it takes only hostname instead of complete host. This was causing an Invalid audience URI as port number was missing in the token & SP was returning 401 unauthorized due to invalid audience URI.

I have fixed in my local by changing hostname to host while URL parse on the below line.
`var sharepointhostname = url.parse(this._siteUrl).host;`.

This has fixed my issue, but it of course is not a fix in the codebase.

Can i fork into your repo and doing a pull request to make this a part of this solution?

Thanks,
Raghu

**Comment by s-KaiNet** [comment]
Thanks, Raghu,   
I understand your frustration, you are trying to use `sppull` but see 401 errors again and again.. :) but thanks for the help and deep investigations.   

New version is `1.2.3` just published.
