### ISSUE TITLE
403:Forbidden Error on sharepoint online rest api on reading /updating a sharepoint list

### ISSUE THREAD

**Issue by sree00718** [s-KaiNet/node-sp-auth#78]
I am using the same code as mentioned here(https://github.com/s-KaiNet/sp-request) to update my sharepoint list from nodejs but iam getting 403 forbidden error-{ StatusCodeError: 403 - {"error":{"code":"-2147024891, System.UnauthorizedAccessException","message":{"lang":"en-US","value":"Access denied. You do not have permission to perform this action or access this resource."}}},When the post request is made to update the list(spr.requestDigest('https://xyz.sharepoint.com/sites/dev')) after getting the access token. 

i registered the app on sharepoint online to get the client id and secret. Following is the app manifest.
```
<AppPermissionRequests AllowAppOnlyPolicy="true">
  <AppPermissionRequest Scope="http://sharepoint/content/sitecollection/web" Right="FullControl"/>
</AppPermissionRequests>

```
I was facing similar issue with postman as well.
Is the issue related to scope? or SSL?

**Comment by s-KaiNet** [comment]
As the message says, you don't have permissions. How you have added permissions to your app registration? Have you used the same site collection, from where you're trying to get data?

**Comment by sree00718** [comment]
During the app registration process, scope was set to  Scope="http://sharepoint/content/sitecollection/web" should it be something else?
App registration was done by registrating on the link :https://[TENANT -NAME].sharepoint.com/_layouts/15/appregnew.aspx

**Comment by s-KaiNet** [comment]
![image](https://user-images.githubusercontent.com/10658276/80810589-dfa5dd80-8bcc-11ea-935b-6b1023cf4903.png)
Which scope do you mean?

**Comment by sree00718** [comment]
> ![image](https://user-images.githubusercontent.com/10658276/80810589-dfa5dd80-8bcc-11ea-935b-6b1023cf4903.png)
> Which scope do you mean?

in the app manifest <AppPermissionRequests AllowAppOnlyPolicy="true">
  <AppPermissionRequest Scope="http://sharepoint/content/sitecollection/web" Right="FullControl"/>
</AppPermissionRequests> after this step.

**Comment by s-KaiNet** [comment]
Please try `http://sharepoint/content/sitecollection` scope instead.

**Comment by sree00718** [comment]
> Please try `http://sharepoint/content/sitecollection` scope instead.

i see will definitely try it out. would that be the issue? it will take some time for me to change the scope back again as i need to take permission from my boss.  app domain and redirect uri were set to localhost and https://localhost .Is that okay?

**Comment by s-KaiNet** [comment]
> would that be the issue?  

Yes, that might be the issue. 

> app domain and redirect uri were set to localhost and https://localhost .Is that okay?  

If you're going to use app-only authentication, i.e. use client id and client to generate an access token, then it's ok.   

> it will take some time for me to change the scope back again

You can register a dev tenant and do experiments there, it will be a lot faster.

**Comment by sree00718** [comment]
I tried with scope set to http://sharepoint/content/sitecollection with fullcontrol access ,still the same issue. 403 forbidden with reading and writing to list

**Comment by sree00718** [comment]
Could it be that scope doesnt give permission for custom list's? When i tried  http://sharepoint/content/sitecollection/web/list . I was prompted to make a choice for which specific list i needed the access to ,where i could not see my custom create list.(Before clicking trust it).Not sure,any idea would help a lot.

**Comment by sree00718** [comment]
Issue resolved. I had registered the bot at the wrong place. Registration when done under the correct site name,all worked fine. Thanks without creating a dev tenant and waiting for trying out different combination would def slowed down narrowing the issue.I'm closing the issue.Thanks a lot :)

**Comment by mukeshbhati2011** [comment]
hey @sree00718 i am facing same issue what do you mean by "I had registered the sharepoint addin at the wrong address. Registration when done under the correct site name,all worked fine" and what you used as Scope finally ?

**Comment by gide02** [comment]
Hello, I'm currently facing same issue. Can you show us the steps you made to resolve the issue?
