### ISSUE TITLE
On-Demand and Electron@latest

### ISSUE THREAD

**Issue by koltyakov** [s-KaiNet/node-sp-auth#79]
I had a couple of requests with On-Demand strategy with issues dependent on the installed Electron version.

It would be great to check what was introduced in Electron v8 which breaks the current implementation of On-Demand strategy. I didn't have such a chance yet but maybe will take a look sooner.

The existing workaround (which I personally stick to for a while) is rolling back to v6, it is acceptable but not optimal as the default expectation for a user is to install the latest one. Looks like Electron always introduces breaking changes in arguments. Maybe we should have a strategy to support the last 2-3 versions and have fallback approaches.

**Comment by s-KaiNet** [comment]
Yeah... electron constantly gives some issues regarding version. I would rather add support for one version of the electron, which works and specify this in the documentation. For example current latest 8.x

**Comment by s-KaiNet** [comment]
:ship: `node-sp-auth@2.5.9`

**Comment by s-KaiNet** [comment]
They changed the way, how cookies are handled (now promises-based). But that was the only change. Tested with 8.x and upcoming 9.x - works fine.

**Comment by koltyakov** [comment]
Thank you Sergei, as always!
