### ISSUE TITLE
Keep getting 401 unauthorized when using axios

### ISSUE THREAD

**Issue by Enado95** [s-KaiNet/node-sp-auth#80]
I keep getting 401 unauthorized when using axios. Works fine with request-promise

```
return spauth
    .getAuth(process.env.SHAREPOINT_SITE_URL, {
      username: `${process.env.SHAREPOINT_USER}`,
      password: `${process.env.SHAREPOINT_USER_PASSWORD}`,
      domain: `${process.env.NCB_DOMAIN}`
    })
    .then(data => {
      let headers = data.headers
      headers['Accept'] = 'application/xml;odata=verbose'
      let requestOpts = data.options
      requestOpts.method = 'GET'
      requestOpts.json = true;
      requestOpts.headers = headers
      requestOpts.url = `${process.env.SHAREPOINT_SITE_URL}${library}/${fileName}`
      requestOpts.httpsAgent = new https.Agent({ rejectUnauthorized: false })
      requestOpts.timeout = 10000

      console.log(requestOpts);
      
      axios(requestOpts)
        .then(response => { console.log(response.data) })
        .catch(err => {console.log(err)})
```

**Comment by koltyakov** [comment]
This worked for me:

```javascript
//@ts-check

const { getAuth } = require('node-sp-auth');
const { AuthConfig } = require('node-sp-auth-config');
const axios = require('axios').default;

(async () => {

  const { siteUrl, authOptions } = await new AuthConfig().getContext();
  const { headers, options } = await getAuth(siteUrl, authOptions);

  const requestConfig = {
    httpAgent: options.agent, // <-- this was missed for NTLM to work
    ...options,
    headers,
    timeout: 10000
  };

  const odataHeaders = {
    'Accept': 'application/json;odata=verbose',
    'Content-Type': 'application/json;odata=verbose'
  };

  const { data } = await axios.get(
    `${siteUrl}/_api/web?$select=Title`,
    {
      ...requestConfig,
      headers: {
        ...requestConfig.headers,
        ...odataHeaders
      }
    }
  );

  console.log(data);

})()
  .catch(console.log);
```

**Comment by koltyakov** [comment]
Almost never used Axios before, it can be even more robust to provide creds stuff as defaults. And use Axios client instance with less code boilerplate.

```javascript
//@ts-check

const { getAuth } = require('node-sp-auth');
const { AuthConfig } = require('node-sp-auth-config');
const axios = require('axios').default;

async function getSPClient() {
  const { siteUrl, authOptions } = await new AuthConfig().getContext();
  const { headers, options } = await getAuth(siteUrl, authOptions);

  const instance = axios.create();
  instance.defaults.headers = headers;
  if (options.agent) {
    if (options.agent.protocol === 'https:') {
      instance.defaults.httpsAgent = options.agent;
    } else {
      instance.defaults.httpAgent = options.agent;
    }
  }
  instance.defaults.baseURL = siteUrl;

  return instance;
};

(async () => {

  const client = await getSPClient();

  const odataConf = {
    headers: {
      'Accept': 'application/json;odata=verbose',
      'Content-Type': 'application/json;odata=verbose'
    }
  };

  const { data } = await client.get(`/_api/web?$select=Title`, odataConf);

  console.log(data);

})()
  .catch(console.log);
```

**Comment by Enado95** [comment]
> Almost never used Axios before, it can be even more robust to provide creds stuff as defaults. And use Axios client instance with less code boilerplate.
> 
> ```js
> //@ts-check
> 
> const { getAuth } = require('node-sp-auth');
> const { AuthConfig } = require('node-sp-auth-config');
> const axios = require('axios').default;
> 
> async function getSPClient() {
>   const { siteUrl, authOptions } = await new AuthConfig().getContext();
>   const { headers, options } = await getAuth(siteUrl, authOptions);
> 
>   const instance = axios.create();
>   instance.defaults.headers = headers;
>   if (options && options.agent) {
>     if (options.agent.protocol === 'https:') {
>       instance.defaults.httpsAgent = options.agent;
>     } else {
>       instance.defaults.httpAgent = options.agent;
>     }
>   }
>   instance.defaults.baseURL = siteUrl;
> 
>   return instance;
> };
> 
> (async () => {
> 
>   const client = await getSPClient();
> 
>   const odataConf = {
>     headers: {
>       'Accept': 'application/json;odata=verbose',
>       'Content-Type': 'application/json;odata=verbose'
>     }
>   };
> 
>   const { data } = await client.get(`/_api/web?$select=Title`, odataConf);
> 
>   console.log(data);
> 
> })()
>   .catch(console.log);
> ```

This solution solved the issue. The first one still returned unauthorized. Thanks!

**Comment by koltyakov** [comment]
`httpAgent`, `httpsAgent` properties. In the first one, I put only `httpAgent`, in global setup improved if a bit to work with http/https and not only NTLM but other strategies as well.

**Comment by Enado95** [comment]
How do I configure authConfig to pass in the url and authOptions within the code and not command line?

**Comment by koltyakov** [comment]
Using `node-sp-auth-config` is optional. You can provide creds to node-sp-auth directly as you did before (in your code sample). Or through SPAUTH_ [environment variables](https://github.com/koltyakov/node-sp-auth-config#environment-variables), not forgetting defining prod mode to avoid stuck CLI in a headless environment.

**Comment by Enado95** [comment]
Okay i took another look at your code I saw thats it’s not needed. I just need to create the axios instance. Thanks

**Comment by koltyakov** [comment]
Happy coding!
