### ISSUE TITLE
"Error: Protocol error (Network.setCookies): Invalid cookie fields" when using ClientId and ClientSecret

### ISSUE THREAD

**Issue by mhintner** [s-KaiNet/node-sp-auth#86]
Hi,
I'm using your library in combination with https://github.com/koltyakov/sp-auth-puppeteer-sample for generating PDFs based on SharePoint Online News pages. This works fine if I supply username/password. But the requirement is to use ClientId/Secret - which produces the error: "Error: Protocol error (Network.setCookies): Invalid cookie fields".
Do you have any info on this?
The second question would be if it is possible to provide the SiteURL during runtime (and not stored in private.json)?
Thanks,
Markus

**Comment by koltyakov** [comment]
@mhintner,

WIth AddIn-Only, unfortunately, is not possible opening pages, it only allows consuming APIs.

**Comment by mhintner** [comment]
Very unfortunate limitation of SPO, but thanks anyway.
