### ISSUE TITLE
Access has been blocked by Conditional Access policies

### ISSUE THREAD

**Issue by farzd** [s-KaiNet/node-sp-auth#88]
Hello, i've tried both 
- User credentials (SAML/ADFS) 
- Add-In Only permissions 

**User credentials** 
Tried this sample
```
const spauth = require('node-sp-auth');
const request = require('request-promise');

spauth
  .getAuth('https://farzadq.sharepoint.com/sites/TestCommSite/', {
    username: 'farzad@farzadq.onmicrosoft.com',
    password: 'xxxx'
  })
  .then(data => {
    var headers = data.headers;
    headers['Accept'] = 'application/json;odata=verbose';

    request.get({
      url: 'https://farzadq.sharepoint.com/sites/TestCommSite/_api/web',
      headers: headers,
      json: true
    }).then(response => {
      console.log(response.d.Title);
    });
  });
```
i get 
```Access has been blocked by Conditional Access policies```

**Add-In Only permissions** 
Following: https://github.com/s-kainet/node-sp-auth/wiki/SharePoint-Online-addin-only-authentication
i get 
```'{"error":"invalid_request","error_description":"Token type is not allowed."}' }```

i was trying sp-rest-proxy  https://github.com/koltyakov/sp-rest-proxy/issues/117 but have now followed my path of failure to here. I checked Azure directory and i dont have premium so i cant set new policies so there should not be any by default?

**Comment by koltyakov** [comment]
Looks as CustomAppAuthentication is disabled on the tenant so AddIn-Only can't work (https://sharepoint.stackexchange.com/questions/284402/sharepoint-online-authorization-issue-token-type-is-not-allowed).

**Comment by farzd** [comment]
@koltyakov i am able to generate client app id (appregnew.aspx) and register it via 
https://farzadq-admin.sharepoint.com/_layouts/15/appinv.aspx

so i have my client id/secret but still results in that error after a request

**Comment by koltyakov** [comment]
@farzd, 

New tenants by default block AddIn-Only auth for some time now. You still can register and configure an app, I don't think that with a custom app auth blocked app inventory is also locked.

If the custom app auth is disabled, it can be enabled with the following command:

```powershell
set-spotenant -DisableCustomAppAuthentication $false
```

**Comment by farzd** [comment]
@koltyakov Thanks, unable to do it on OSX via powershell. I've installed the MS module but commands dont work. 
Anyway i've tried it on my clients sharepoint and the auth is working so you're guess is correct.

Thanks for your time.
