### ISSUE TITLE
unable to compile

### ISSUE THREAD

**Issue by quantrpeter** [s-KaiNet/node-sp-auth#89]
Hi
   Tried nodejs v10, v12, v15:

```
node_modules/node-sp-auth/node_modules/got/dist/source/types.d.ts:205:83 - error TS2709: Cannot use namespace 'PCancelable' as a type.    
```

Thanks

**Comment by koltyakov** [comment]
The error isn't connected with a Node version, but TypeScript specific.

Such TypeScript errors are common when local TS settings/version is different from the one used in the library. Should be forced to ignore in `tsconfig.json` by setting `skipLibCheck`:

```json
{
  "compilerOptions": {
    "skipLibCheck": true
  }
}
```

**Comment by quantrpeter** [comment]
thanks, it works
