### ISSUE TITLE
Azure AD

### ISSUE THREAD

**Issue by wmertens** [s-KaiNet/node-sp-auth#94]
It seems MS is recommending Azure AD for new tenants (but not removing add-in credentials).

Is it possible to use that, or will it be a lot of work to support it?

> For new tenants, apps using an ACS app-only access token is disabled by default. We recommend using the Azure AD app-only model which is modern and more secure.

-- https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-apponly-azureacs

**Comment by s-KaiNet** [comment]
For Azure AD you can use other libraries, like msal for example. I'm not planning to add Azure AD support here.

**Comment by tarundhillon** [comment]
@wmertens what approach did you take for Azure AD ? I am also faced with a similar situation.
