### ISSUE TITLE
The user account {EmailHidden} does not exist in the mycompany.onmicrosoft.com directory

### ISSUE THREAD

**Issue by Aymkdn** [s-KaiNet/node-sp-auth#97]
Hi,

I try to access my company's Sharepoint online (https://mycompany.sharepoint.com/sites/Demo).

Doing the below returns an error:
```js
const spauth = require('node-sp-auth');
const request = require('request-promise');

spauth
  .getAuth('https://mycompany.sharepoint.com/sites/Demo/', {
    username: 'aymkdn@mycompany.onmicrosoft.com',
    password: 'MyPassWord',
    online: true
  })
  .then(data => {
    var headers = data.headers;
    headers['Accept'] = 'application/json;odata=verbose';

    request.get({
      url: 'https://mycompany.sharepoint.com/sites/Demo/_api/web',
      headers: headers,
      json: true
    }).then(response => {
      console.log(response.d.Title);
    });
  });
```

It returns:
```xml
<S:Fault>
  <S:Code>
    <S:Value>S:Sender</S:Value>
    <S:Subcode>
      <S:Value>wst:FailedAuthentication</S:Value>
    </S:Subcode>
  </S:Code>
  <S:Reason>
    <S:Text xml:lang="en-US">Authentication Failure</S:Text>
  </S:Reason>
  <S:Detail>
    <psf:error xmlns:psf="http://schemas.microsoft.com/Passport/SoapServices/SOAPFault">
      <psf:value>0x80048821</psf:value>
      <psf:internalerror>
        <psf:code>0x80048821</psf:code>
        <psf:text>AADSTS50034: The user account {EmailHidden} does not exist in the mycompany.onmicrosoft.com directory. To sign into this application, the account must be added to the directory.</psf:text>
      </psf:internalerror>
    </psf:error>
  </S:Detail>
</S:Fault>
```

My email in my company is `aymkdn@mycompany.com`  and it's also what I use to log in when using the webbrowser. I tried to replace `aymkdn@mycompany.onmicrosoft.com`  with `aymkdn@mycompany.com`, and I also tried different variations… But it ends with the same error.

Do you have any advice?

Thanks

**Comment by s-KaiNet** [comment]
Hello, 

for me, it looks likes [legacy authentication](https://www.vansurksum.com/2020/03/01/microsoft-is-going-to-disable-basic-legacy-authentication-for-exchange-online-what-does-that-actually-mean-and-does-that-impact-me/) is disabled for your tenant. That might be reason. In that case you can only use client id\secret auth.

**Comment by Aymkdn** [comment]
I guess it will be https://github.com/s-KaiNet/node-sp-auth/wiki/SharePoint%20Online%20addin%20only%20authentication ? But if I understand correcly I'll need a tenant admin to give access to my app?

**Comment by s-KaiNet** [comment]
Tenant admin is not a requirement, you can configure on a per-site collection basis. Check out [point 8](https://github.com/s-KaiNet/node-sp-auth/wiki/SharePoint%20Online%20addin%20only%20authentication#configuration-required) from the same doc.

**Comment by Aymkdn** [comment]
Yeah it seems to work! Thanks ♥️
